### ISSUE TITLE
io.netty.util.internal.OutOfDirectMemoryError

### ISSUE THREAD

**Issue by rakeshnambiar** [gatling/gatling#3358] opened 2017-10-03 15:41 UTC
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 251658247, max: 259522560)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:522)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:476)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:766)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:742)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:333)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:170)
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:131)
        at io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl.allocate(AdaptiveRecvByteBufAllocator.java:104)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
16:36:33.433 [DEBUG] o.a.n.c.DefaultChannelPool - Entry count for : http://gatling.io:80 : 1
16:36:33.545 [DEBUG] o.a.n.NettyResponseFuture - asyncHandler.onThrowable
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at java.nio.HeapCharBuffer.toString(HeapCharBuffer.java:567)
        at java.nio.CharBuffer.toString(CharBuffer.java:1241)
        at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:605)
        at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:971)
        at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:966)
        at org.asynchttpclient.netty.util.ByteBufUtils.decodeNonOptimized(ByteBufUtils.java:45)
        at org.asynchttpclient.netty.util.Utf8ByteBufCharsetDecoder.decode(Utf8ByteBufCharsetDecoder.java:191)
        at org.asynchttpclient.netty.util.Utf8ByteBufCharsetDecoder.decodeUtf8(Utf8ByteBufCharsetDecoder.java:47)
        at org.asynchttpclient.netty.util.ByteBufUtils.byteBuf2String(ByteBufUtils.java:54)
        at io.gatling.http.response.StringResponseBody$.apply(ResponseBody.scala:70)
        at io.gatling.http.response.ResponseBuilder.build(ResponseBuilder.scala:197)
        at io.gatling.http.ahc.AsyncHandler.withResponse(AsyncHandler.scala:126)
        at io.gatling.http.ahc.AsyncHandler.onThrowable(AsyncHandler.scala:143)
        at org.asynchttpclient.netty.NettyResponseFuture.abort(NettyResponseFuture.java:247)
        at org.asynchttpclient.netty.request.NettyRequestSender.abort(NettyRequestSender.java:406)
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.exceptionCaught(AsyncHttpClientHandler.java:199)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:259)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:251)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:259)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:251)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:259)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:251)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:426)
        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:88)
        at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:147)

POM File:
<properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <gatling.version>2.3.0</gatling.version>
    <gatling-plugin.version>2.2.4</gatling-plugin.version>
    <scala-maven-plugin.version>3.3.1</scala-maven-plugin.version>
    <test.scalaClass>Live</test.scalaClass>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.gatling.highcharts</groupId>
      <artifactId>gatling-charts-highcharts</artifactId>
      <version>${gatling.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>${scala-maven-plugin.version}</version>
      </plugin>
      <plugin>
        <groupId>io.gatling</groupId>
        <artifactId>gatling-maven-plugin</artifactId>
        <version>${gatling-plugin.version}</version>
        <configuration>
          <configFolder>${project.basedir}/src/test/resources</configFolder>
          <dataFolder>${project.basedir}/src/test/resources/data</dataFolder>
          <resultsFolder>${project.basedir}/target/gatling/results</resultsFolder>
          <bodiesFolder>${project.basedir}/src/test/resources/bodies</bodiesFolder>
          <simulationsFolder>${project.basedir}/src/test/scala/epmc</simulationsFolder>
          <runDescription>Gatling Demo</runDescription>
          <runMultipleSimulations>true</runMultipleSimulations>
          
          
          <simulationClass>${test.scalaClass}</simulationClass>
          
          
          
          
          
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>execute</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>

Java version: 1.8.0_144,

**Comment by slandelle** [comment] 2017-10-03 15:49
Most likely, you're either storing too much data in your virtual users session and fill your heap, of you're writing way too fast for your system under test to read.

Also, when trying to open an issue, please provide more information, typically here a heap dump, and better, a way to reproduce.

Closing for now as I thing the issue is on your side. Please report again if you have more information that would point to an issue on the Gatling side.

**Closed by slandelle** 2017-10-03 15:49 UTC

**Comment by rakeshnambiar** [comment] 2017-10-03 15:55
Hi @slandelle .. Pls find the log back xml and test script below. Kindly advice.

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<contextListener class="ch.qos.logback.classic.jul.LevelChangePropagator">
		<resetJUL>true</resetJUL>
	</contextListener>

	<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>%d{HH:mm:ss.SSS} [%-5level] %logger{15} - %msg%n%rEx</pattern>
			<immediateFlush>false</immediateFlush>
		</encoder>
	</appender>

	
	
	
	
	

	<root level="WARN">
		<appender-ref ref="CONSOLE" />
	</root>

</configuration>


Script
---------------------------------------------------------------------------------
val feeder = csv("epmcData.csv")

  val header = Map(
    "Content-Type" -> "text/xml;charset=UTF-8",
    "SOAPAction" -> "",
    "Operation" -> "searchPublications",
    "Style" -> "Document",
    "Type" -> "Request-Response",
    "Host" -> "ves-hx-30:8090"
    )

  val scn = scenario("SOAP API Without Snippets")
      .feed(feeder)
      .exec(http("Search_Publications")
      .post("")
        .headers(header)
          .body(StringBody("
             "${SearchKey}" "))
             .check(status.is(200))
              .check(bodyString.transform(_.contains("resultList")).is(true))
               .check(bodyString.transform(_.contains("authorList")).exists)
                  .check(bodyString.transform(_.contains("${SearchKey}")).exists)
      )

  setUp(scn.inject(atOnceUsers(50)).protocols(httpConf))
    .assertions(
        global.successfulRequests.percent.gte(100)
    )

**Comment by slandelle** [comment] 2017-10-03 16:01
Sorry, but I can't reproduce with just a piece of your test (no feeder, no application to be tested).
Please try trimming your test down and maybe provide a mock of your application.
As I said, also investigate a heap dump so you can check what uses so much memory (maybe the feeder).
If you can't, I'm afraid I can't help. We only investigate on remote environments for our customers.

**Comment by rakeshnambiar** [comment] 2017-10-03 16:05
Hi @slandelle ... the feeder looks like below. Test is PASS when trying with 10 users and it's failing with 20.

SearchKey
"endometrial hyperplasia, atypical"
senior AND connect
"ISSN:""0934-9820"""
"AUTH:""De Anna D"""
Corneal Transplantation
pathophisiology of diabetes
"ISSN:""2090-052x"""
cueva
PMC3480808
CANMAT TREATMENT OF BIPOLAR DEPRESSION
improving hospice nurse documentation pain
"AUTH:""Wilson JA"""
"AUTH:""Carlson KJ"""
"AUTH:""Williams LM"""
child develpoment
pth AND amino AND acid
electronic AND publishing
glick and fiske ambivalent
"ISSN:""1535-7732"" AND AUTH:""Horgan AM"""
"KW:""Dental Cavity Preparation"" AND PUB_TYPE:""clinical trial"""
berg balance test
"ISSN:""1807-5932"""
The confounding issue of sex and stroke
"AUTH:""Mäenpää P"""
kidney transplantation hypertension
9529088
views of glaucoma patients on provision of follow-up
Gemination and twinning in the permanent dentition
Joint AND publication
"(AUTH:""swedlow j"" ) PUB_YEAR:[2008 TO 2012]"
Hypothermia as a cytoprotective strategy in ischemic tissue injury
"KW:""Mesna"""
profile postural sport
discuss electronic health records]
"AUTH:""Pannone G AND AUTH:Rubini C"""
"KW:""Jaundice"""
"AUTH:""Nishina S"""
anti TNF and demyelination
"AUTH:""Nikolaeva L"""
"rhizobium AND AUTH:""Skorupska A"""
17050571 OR PMC2859134
"ISSN:""1879-1271"""
"stroke, cerebrovascular, risk factors"
"KW:""Human Growth Hormone"" 2006"
TITLE:Generalised anxiety disorder JOURNAL:Clinical evidence PUB_YEAR:2004
"AUTH:""Yuksel S"""
"AUTH:""Stevenson LW"""
"KW:""Coitus"" first"
"AUTH:""Gispen JG"""
Effects of age on job performance of an office worker

**Comment by rakeshnambiar** [comment] 2017-10-04 09:13
Hi @slandelle ..could you pls tell me your email id? I will share the google drive url which contains my dump

**Comment by slandelle** [comment] 2017-10-04 09:14
slandelle@gatling.io

**Comment by rakeshnambiar** [comment] 2017-10-04 09:16
Thanks

**Comment by rakeshnambiar** [comment] 2017-10-04 09:18
Kindly check your email

**Comment by rakeshnambiar** [comment] 2017-10-04 16:08
Hi @sandello ... I am able to run the same tests with JMeter and observers the below lines are causing issues. Could you please suggest the alternative options to validate the response and sprint the request/response on the log file?

.check(bodyString.transform(_.contains("resultList")).is(true))
.check(bodyString.transform(_.contains("authorList")).exists)
.check(bodyString.transform(_.contains("${SearchKey}")).exists)
.extraInfoExtractor(extraInfo => List(extraInfo.request, extraInfo.response.body.string,extraInfo.session))
