### ISSUE TITLE
Jenkins plugin causes CSS layout problem when chart is rendered.

### ISSUE THREAD

**Issue by meteorfox** [gatling/gatling#2543] opened 2015-01-30 22:05 UTC
Since upgrading to Jenkins 1.597 the plugin doesn't render properly. 

Here's a screenshot:
![projectscreenshot](https://cloud.githubusercontent.com/assets/232300/5984222/d5dfdaf6-a899-11e4-87a9-a729dad5ddfc.png)

**Comment by slandelle** [comment] 2015-01-31 10:10
Looks like a duplicate of #2527.
Great move, Jenkins!

**Comment by pwielgolaski** [comment] 2015-03-29 16:33
it seems that I was able to fix it check pull request https://github.com/jenkinsci/gatling-plugin/pull/9

**Comment by pdalpra** [comment] 2015-03-30 10:10
Fixed by jenkinsci/gatling-plugin/pull/9

**Closed by pdalpra** 2015-03-30 10:10 UTC
