### ISSUE TITLE
Core: tryMax - should be reported/used as One Record

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4324] opened 2022-09-05 13:34 UTC
Gatling: 3.8.3
OS: Windows 10 Pro
JDK: jdk-17.0.4

I'm not sure if this is a bug but reading documentation I understood that tryMax is used to get correct response but if failed I should get information about failiture of this response - main question is if this should be "only one record", I think this should be. So in console and reports I should have only one record about this but I get 5.
Simulation:
```
public class TryMaxStatusCodeSimulation extends Simulation {

    HttpProtocolBuilder httpProtocol =
            http
                    .baseUrl("https://postman-echo.com");

    ScenarioBuilder scn =
            scenario("GeMi_TryMaxStatusCodeSimulation")
                    .tryMax(5).on(
                            exec(
                                    http("GeMi_TryMaxStatusCodeSimulation_get")
                                            .get("/status/414")
                            ));

    {
        setUp(scn.injectOpen(atOnceUsers(1)).protocols(httpProtocol));
    }
}

```

simulation.log:
```
RUN	pl.gemiusz.TryMaxStatusCodeSimulation	trymaxstatuscodesimulation	1662383893675	 	3.8.3
USER	GeMi_TryMaxStatusCodeSimulation	START	1662383895308
REQUEST		GeMi_TryMaxStatusCodeSimulation_get	1662383895271	1662383895998	KO	status.find.in([200, 209], 304), found 414
REQUEST		GeMi_TryMaxStatusCodeSimulation_get	1662383896049	1662383896305	KO	status.find.in([200, 209], 304), found 414
REQUEST		GeMi_TryMaxStatusCodeSimulation_get	1662383896308	1662383896508	KO	status.find.in([200, 209], 304), found 414
REQUEST		GeMi_TryMaxStatusCodeSimulation_get	1662383896510	1662383896829	KO	status.find.in([200, 209], 304), found 414
REQUEST		GeMi_TryMaxStatusCodeSimulation_get	1662383896831	1662383897148	KO	status.find.in([200, 209], 304), found 414
USER	GeMi_TryMaxStatusCodeSimulation	END	1662383897154
```

Console:
![image](https://user-images.githubusercontent.com/30750006/188460712-a397ed30-8636-4cfc-8e8a-8d384ec3cfdd.png)

![image](https://user-images.githubusercontent.com/30750006/188460823-46558470-753a-4a7a-a3d5-66c5afac7ec1.png)

**Comment by Isammoc** [comment] 2022-09-05 13:42
Technically, there were 5 requests that are all KO.
I'm not sure what is the wanted behavior of this `tryMax`.
My understanding is that it will loop over its body until the body is successful, but it will let the session status as is. if the body fails 5 times, the last status will be "fail", so the tryMax.
But there are still failed requests in it.

**Comment by gemiusz** [comment] 2022-09-05 13:47
Yes but I think it should be "ONLY ONE" reported.

**Comment by gemiusz** [comment] 2022-09-05 15:01
As I understood **tryMax** should be as some "internal try until positive result or until last negative call" but I can be wrong - I understood that from documentation and from own experience :)

**Comment by Isammoc** [comment] 2022-09-05 15:17
My own understanding, too, but I think `tryMax` is error tolerant for functional aspect, but not for performance ones.
If a request took more than a threshold (even the ones in the body of `tryMax`) we should ring an alert.
The user is allowed to continue to read their scenario, but performance must be tracked.

**Comment by slandelle** [comment] 2022-09-05 15:34
The current strategy is to log every request:
* failed requests are part of the traffic against the server
* users might be interested in the response time of those requests
* users are probably interested in how many retried they needed to get the expected status

If you want to group the whole sequence, you should wrap your `tryMax` with a group.

**Comment by Isammoc** [comment] 2022-09-05 15:49
So, we can close this issue as this is not a bug, sorry
If the misunderstanding comes from the documentation, a contribution to it may improve understanding of future users.

**Closed by Isammoc** 2022-09-05 15:49 UTC

**Comment by gemiusz** [comment] 2022-09-06 19:39
> We don't say anywhere that errors are silently swallowed.
So the current behavior is definitely the expected one.

I'm not agree with you because **"interrupt and start over from the beginning"** can be understood as **"don't do anything (don't report, don't save in simulation.log ect.) and start again"** unless all conditions in tryMax block are pass.

How this should work (a bit similar to groups) :
- if all conditions from tryMax are satisfied report them only once from current iteration,
- if one conditions of many is not satisfied return to begining and try next iteration without report anything,
- if it's last iteration report all from this iteration.

**Comment by Isammoc** [comment] 2022-09-07 06:39
> "interrupt and start over from the beginning" can be understood as "don't do anything (don't report, don't save in simulation.log ect.) and start again"

Why?
* **"interrupt"** => do not execute following steps (in block)
* **"start over"** => try again since the first step (in block)

There is no notion of reporting, storage, logging or anything.
So the usual behavior apply: for each executed request, store in log and report.

As you struggle with that, you may want to contribute to the documentation to express that the usual behavior still apply. But I agree with @slandelle, there is no reason whatsoever that it will be otherwise.

In the sample from @slandelle, why don't we report the results and time for the requests? The server did receive the requests, the usage is traced in the APM and there may be a performance issue (the answer take more than 300ms for instance).
So, we cannot silent the request.

**Comment by slandelle** [comment] 2022-09-07 07:27
I've pushed a doc change to explicitly state the logging behavior.
