### ISSUE TITLE
User Agent header is empty on HTTP redirects

### ISSUE THREAD

**Issue by tomasliubinas** [gatling/gatling#2696] opened 2015-04-28 16:07 UTC
User Agent header supplied over .userAgentHeader() is not filled once more after HTTP redirect has been performed.

Reproduced in Gatling version: 2.1.4

**Comment by slandelle** [comment] 2015-04-28 16:44
Duplicate of #2548, fixed in 2.1.5.

**Closed by slandelle** 2015-04-28 16:44 UTC
