### ISSUE TITLE
when Using a proxy and using Https a Exception was thrown

### ISSUE THREAD

**Issue by skytraveler** [gatling/gatling#2879] opened 2015-12-21 11:14 UTC
[ERROR] [12/21/2015 19:05:10.611] [GatlingSystem-akka.actor.default-dispatcher-3] [akka://GatlingSystem/user/userEnd] com.ning.http.client.ConnectionPoolPartitioning$ProxyPartitionKey cannot be cast to java.lang.String
java.lang.ClassCastException: com.ning.http.client.ConnectionPoolPartitioning$ProxyPartitionKey cannot be cast to java.lang.String
	at io.gatling.http.config.HttpProtocol$$anon$1.select(HttpProtocol.scala:178)
	at com.ning.http.client.providers.netty.channel.pool.DefaultChannelPool.flushPartitions(DefaultChannelPool.java:325)
	at com.ning.http.client.providers.netty.channel.ChannelManager.flushPartitions(ChannelManager.java:486)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.flushChannelPoolPartitions(NettyAsyncHttpProvider.java:99)
	at io.gatling.http.config.HttpProtocol.userEnd(HttpProtocol.scala:174)
	at io.gatling.core.config.Protocols$$anonfun$1$$anonfun$apply$1.apply(Protocols.scala:46)
	at io.gatling.core.config.Protocols$$anonfun$1$$anonfun$apply$1.apply(Protocols.scala:46)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at io.gatling.core.config.Protocols$$anonfun$1.apply(Protocols.scala:46)
	at io.gatling.core.config.Protocols$$anonfun$1.apply(Protocols.scala:46)
	at io.gatling.core.session.Session.terminate(Session.scala:216)
	at io.gatling.core.action.UserEnd.execute(UserEnd.scala:45)
	at io.gatling.core.action.Action$$anonfun$receive$1.applyOrElse(Actions.scala:29)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:22)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

19:05:10.619 [ERROR] i.g.c.a.UserEnd - Actor io.gatling.core.action.UserEnd@2060a928 crashed on message Some(Session(xxxx,4140991920831115762-0,Map(),1450695910271,114,OK,List(),<function1>))
java.lang.ClassCastException: com.ning.http.client.ConnectionPoolPartitioning$ProxyPartitionKey cannot be cast to java.lang.String
	at io.gatling.http.config.HttpProtocol$$anon$1.select(HttpProtocol.scala:178) ~[gatling-http-2.1.7.jar:2.1.7]
	at com.ning.http.client.providers.netty.channel.pool.DefaultChannelPool.flushPartitions(DefaultChannelPool.java:325) ~[async-http-client-1.9.30.jar:na]
	at com.ning.http.client.providers.netty.channel.ChannelManager.flushPartitions(ChannelManager.java:486) ~[async-http-client-1.9.30.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.flushChannelPoolPartitions(NettyAsyncHttpProvider.java:99) ~[async-http-client-1.9.30.jar:na]
	at io.gatling.http.config.HttpProtocol.userEnd(HttpProtocol.scala:174) ~[gatling-http-2.1.7.jar:2.1.7]
	at io.gatling.core.config.Protocols$$anonfun$1$$anonfun$apply$1.apply(Protocols.scala:46) ~[gatling-core-2.1.7.jar:2.1.7]
	at io.gatling.core.config.Protocols$$anonfun$1$$anonfun$apply$1.apply(Protocols.scala:46) ~[gatling-core-2.1.7.jar:2.1.7]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[scala-library-2.11.7.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[scala-library-2.11.7.jar:na]
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206) ~[scala-library-2.11.7.jar:na]
	at io.gatling.core.config.Protocols$$anonfun$1.apply(Protocols.scala:46) ~[gatling-core-2.1.7.jar:2.1.7]
	at io.gatling.core.config.Protocols$$anonfun$1.apply(Protocols.scala:46) ~[gatling-core-2.1.7.jar:2.1.7]
	at io.gatling.core.session.Session.terminate(Session.scala:216) ~[gatling-core-2.1.7.jar:2.1.7]
	at io.gatling.core.action.UserEnd.execute(UserEnd.scala:45) ~[gatling-core-2.1.7.jar:2.1.7]
	at io.gatling.core.action.Action$$anonfun$receive$1.applyOrElse(Actions.scala:29) ~[gatling-core-2.1.7.jar:2.1.7]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
	at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:22) ~[gatling-core-2.1.7.jar:2.1.7]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]

**Comment by slandelle** [comment] 2015-12-21 11:21
Duplicate of #2795

**Closed by slandelle** 2015-12-21 11:21 UTC
