### ISSUE TITLE
file upload POST with asMultipartForm fails with "Stream ended unexpectedly"

### ISSUE THREAD

**Issue by stokpop** [gatling/gatling#3573] opened 2018-10-18 06:34 UTC
Using this code in version 3.0.0-RC4:

        .exec(http("upload-file")
            .post("/files/upload")
            .asMultipartForm
            .bodyPart(
                StringBodyPart("upload", "test from gatling")
                  .fileName("gatling-upload.txt")
            )
        )

fails on SpringBoot file upload server with:

    org.apache.tomcat.util.http.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. Stream ended unexpectedly, 
    org.apache.tomcat.util.http.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly

Checking with Fiddler shows that body content is missing. Same code with Gatling 2.3.1 was working fine.

You can replay this by cloning the following project: [https://github.com/stokpop/afterburner](https://github.com/stokpop/afterburner)

then:
   
    cd afterburner-java
    ../mvnw spring-boot:run

in other window:
    
    cd afterburner-loadtest-gatling/
    ../mvnw gatling:test

Now you can see one failed transaction in gatling run for the file upload and the error in the springboot log.

This is for git commit: _ae81aca1da3515d579c481dcdbca5bb51ea4f587_ (current master head while writing this).

This git commit hash shows it is working with Gatling 2.3.1: _1d2766001ed20644e941ae3fecef5f5bf1afe5df_
Checkout with this hash and repeat steps above.

**Comment by slandelle** [comment] 2018-10-18 06:40
Thanks for reporting.
Actually, this really looks like a duplicate of #3565.
Would you be able to compile Gatling from master and verify?

**Comment by slandelle** [comment] 2018-10-18 07:03
I was able to run on my side (on the train :P).
I confirm your test works just fine with Gatling master.

Thanks

**Closed by slandelle** 2018-10-18 07:03 UTC
