### ISSUE TITLE
HTTP: StringResponseBody sometimes crashes on non US-ASCII chars

### ISSUE THREAD

**Issue by vas78** [gatling/gatling#3213] opened 2016-12-16 14:43 UTC
After migration to Gatling 2.2.3 some of my tests that worked just fine with 2.2.2 started throwing exceptions:
> 15:22:43.778 [ERROR] i.g.h.r.StringResponseBody$ - Response body is not valid UTF-8 bytes
15:22:43.779 [WARN ] i.g.h.a.ResponseProcessor - Request 'ReproducerRequest' failed: jsonPath($.faultMessage.code).find.notExists failed, could not prepare: Boon failed to parse into a valid AST: ArrayIndexOutOfBoundsException: null
15:22:46.210 [ERROR] i.g.h.r.StringResponseBody$ - Response body is not valid UTF-8 bytes
15:22:46.211 [WARN ] i.g.h.a.ResponseProcessor - Request 'ReproducerRequest' failed: jsonPath($.faultMessage.code).find.notExists failed, could not prepare: Boon failed to parse into a valid AST: ArrayIndexOutOfBoundsException: null

I could drill down to the root cause: it happens only with one web-service that returns a relatively large JSON response (approx. 180-190 KB) and following check is included into scenario:
`.check(jsonPath("$.faultMessage.code").notExists)`
Without this check the exception disappears, see a simple reproducer scenario below (I had to remove url and body). Works fine when run single-threaded or for a short duration, but even with 10 RPS and 10 minutes duration throws the above mentioned exceptions.

Seems like this has something to do with the new ByteBufAllocator implementation in 2.2.3. I tried increasing maxThreadLocalCharBufferSize and switching to unpooled allocator but without any luck. Any ideas?

import io.gatling.core.scenario.Simulation
import io.gatling.core.Predef._
import io.gatling.http.Predef.{http, jsonPath, status}

import scala.concurrent.duration._

class ReproducerBoonFailedToParse extends Simulation {

  val protocol = http
    .disableWarmUp
    .userAgentHeader("Gatling")
    .check(status.is(200))
    .contentTypeHeader("application/json")
    .acceptEncodingHeader("gzip")

  val requestBody =
    s"""SOME_JSON_BODY_HERE""".stripMargin

  val scnReproducer =
    scenario("Reproducer")
      .exec(http("ReproducerRequest")
        .post("SOME_TARGET_URL")
        .body(StringBody(requestBody))
        .check(jsonPath("$.faultMessage.code").notExists) //comment to avoid the ArrayIndexOutOfBoundsException
      )

  private val debugDuration = 10 minutes

  setUp(
    scnReproducer.inject(
      constantUsersPerSec(10) during (debugDuration)).protocols(protocol)
  )
}

**Comment by slandelle** [comment] 2016-12-16 14:45
Please provide a reproducer

**Comment by vas78** [comment] 2016-12-16 14:45
Sorry, could not attach a zip file. Added the reproducer in the original issue.

**Comment by slandelle** [comment] 2016-12-16 14:50
Nah. This is not a working reproducer. SOME_JSON_BODY_HERE?

**Comment by vas78** [comment] 2016-12-16 14:51
Request body is actually irrelevant since the problem is the response. I can send you the request/response per email if that`s OK for you.

**Comment by slandelle** [comment] 2016-12-16 14:56
Yeah, that's the response that's relevant. Please provide one. email is fine

**Comment by vas78** [comment] 2016-12-19 13:56
Sorry for the delay, I`m still trying to extract a reproducer that runs on a standalone web server (e.g. apache or nginx). This appears to be a bit tricky since the simple "copy the json to docs dir and serve it as is" does not reproduce the issue... Hopefully will be able to provide an update soon.

**Comment by slandelle** [comment] 2016-12-19 21:54
If the issue is real, it probably has something to do with multiple bytes UTF-8 chars spanned over multiple buffer reads. Then, we're suppose to have this covered.

**Comment by slandelle** [comment] 2017-01-05 08:50
@vas78 Any news? Would it be possible to have a JSON payload sample, please?

**Comment by vas78** [comment] 2017-01-14 20:49
@slandelle I`ve just sent you a sample JSON response per email.

**Comment by slandelle** [comment] 2017-01-15 08:42
Fixed as of https://github.com/AsyncHttpClient/async-http-client/issues/1325

@vas78 thanks for reporting!

**Closed by slandelle** 2017-01-15 08:42 UTC
Labels: Module - HTTP, Type - Bug

**Comment by slandelle** [comment] 2018-09-26 19:14
@TrickyDoodle Your problem has nothing to do with this issue (UTF-8 decoding vs JSON parsing).

Please open a new issue and provide your JSON payload.
