### ISSUE TITLE
Websocket crash on v4 

### ISSUE THREAD

**Issue by gricsi** [gatling/gatling#4237] opened 2022-04-26 08:26 UTC
Version: Gatling 3.7.6
Socket version: v4
Language: Scala dsl 

```
exec(ws("WS - Connect")
      .connect("/socket.io/?EIO=4&transport=websocket")
      .await(twentySeconds)(checkConnectionSessionId))
```

Steps 
- Set connection -> works fine
- Set authenticate call -> works fine
- Keep alive -> also works fine for a short period of time 1-2 minutes

Logs:
- CUSTOM_URL -> shows the correct url i just removed from the security reasons 

```
[DEBUG] i.g.h.a.w.f.WsPerformingCheckState - WebSocket remotely closed while in WsPerformingCheckState state
[DEBUG] i.g.h.a.w.f.WsFsm - Timeout 1420991547 cancelled
[DEBUG] i.g.h.a.w.f.WsFsm - Couldn't cancel timeout because it wasn't set
[DEBUG] i.g.h.a.w.f.WsPerformingCheckState - WebSocket crashed, performing next action
[DEBUG] i.g.h.a.w.f.WsCrashedState - Client issued a text frame but WebSocket was already crashed: 
[DEBUG] i.g.h.a.w.f.WsCrashedState - Reconnecting WebSocket remainingReconnects=1
[DEBUG] i.g.h.a.w.f.WsConnectingState$ - Connecting to wss://[CUSTOM_URL]?EIO=4&transport=websocket
[DEBUG] i.g.h.a.w.f.WsConnectingState - Connected, performing checks before proceeding (no onConnected action)
[DEBUG] i.g.h.a.w.f.WsFsm - Timeout 337450364 scheduled
[DEBUG] i.g.h.a.w.f.WsPerformingCheckState - Received matching message 0{"sid":"MCq4jVkkI27j6R_sAACc","upgrades":[],"pingInterval":25000,"pingTimeout":20000}
[DEBUG] i.g.h.a.w.f.WsFsm - Timeout 337450364 cancelled
[DEBUG] i.g.h.a.w.f.WsPerformingCheckState - Current check success
[DEBUG] i.g.h.a.w.f.WsPerformingCheckState - Check sequences completed successfully
[DEBUG] i.g.h.a.w.f.WsIdleState - Send text frame WS - Keep-alive 3
[DEBUG] i.g.h.a.w.f.WsIdleState - Trigger check after sending text frame
[DEBUG] i.g.h.a.w.f.WsFsm - Timeout 1805533720 scheduled
.. later 
[DEBUG] i.g.h.a.w.f.WsCrashedState - Client issued a text frame but WebSocket was already crashed: 
[DEBUG] i.g.h.a.w.f.WsCrashedState - Client issued text frame but server has closed the WebSocket and max reconnects is reached
[DEBUG] i.g.h.a.w.f.WsCrashedState - Client issued a text frame but WebSocket was already crashed: 
[DEBUG] i.g.h.a.w.f.WsCrashedState - Client issued text frame but server has closed the WebSocket and max reconnects is reached

```

Tried solutions 
- wsAutoReplyTextFrame
- wsAutoReplySocketIo4
- custom keep-alive

None of them solved the issue. 

For feature requests, please:
  * https://github.com/gatling/gatling/issues/3929 -> https://github.com/gatling/gatling/issues/4159 for 
   ping -> pong method  3 -> 2

**Comment by slandelle** [comment] 2022-04-26 13:38
Could you please share:
* a demo app we can use to reproduce your issue?
* any pointer to Socket.io documentation explaining the designed mechanism? I thought Socket.io 4 had switched to server initiated keep-alive.

**Comment by slandelle** [comment] 2022-05-03 12:25
@gricsi Gentle ping.

**Comment by slandelle** [comment] 2022-05-18 11:29
Closing due to lack of answer from the user.
Feel free to reach out with the request information so we can reopen.

**Closed by slandelle** 2022-05-18 11:29 UTC
