### ISSUE TITLE
[Gatling Jenkins Plugin] Reports

### ISSUE THREAD

**Issue by aidylewis** [gatling/gatling#2911] opened 2016-02-12 11:05 UTC
```
jenkins --version
1.643
```

```
gatling jenkins plugin
1.1.1
```

Steps: 
https://github.com/bbc/notes-on-perf-testing/blob/master/ch/jenkins.md#gatling

The simulation runs successfully, but the reports are not displaying
![screen shot 2016-02-12 at 11 02 42](https://cloud.githubusercontent.com/assets/6703997/13005207/340c0ab6-d178-11e5-8301-356fa03a6146.png)

**Comment by slandelle** [comment] 2016-02-12 11:21
Duplicate of #2889, check instructions there.

**Closed by slandelle** 2016-02-12 11:21 UTC

**Comment by slandelle** [comment] 2016-02-26 11:23
Instructions added on the plugin page: https://wiki.jenkins-ci.org/display/JENKINS/Gatling+Plugin
