### ISSUE TITLE
stats.js: Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by tomers** [gatling/gatling#4000] opened 2020-11-05 19:47 UTC
I ran a simulation when one of the URLs contained quoted quotes. This breaks the report HTML file:
```
stats.js:55462 Uncaught SyntaxError: Unexpected identifier
index.html:258 Uncaught ReferenceError: stats is not defined
    at index.html:258
```

The simulation archive is available here: https://www.dropbox.com/s/ukwyrhh2ei7elm4/simulation.zip?dl=0

The offending part from `stats.js`:

```
},"req_https---web-vor-dbe7c": {
        type: "REQUEST",
        name: "https://web.vortex.data.msn.com/collect/v1/t.gif?name=%27Ms.Webi.PageView%27&ver=%272.1%27&appId=%27JS%3AMSN%27&ext-app-env=%27prod%27&ext-javascript-libver=%274.0.0-beta-10%27&ext-user-localId=%27t%3A0672DB74D369646A3C95D40DD2BB6524%27&*baseType=%27Ms.Content.PageView%27&*isJs=False&*title=%27%27&*isLoggedIn=False&*isManual=True&*serverImpressionGuid=%270e4e9122-baae-4eb5-be69-4d1c7d2db891%27&-ver=%271.0%27&-impressionGuid=%270e4e9122-baae-4eb5-be69-4d1c7d2db891%27&-pageName=%27startpage%27&-uri=%27https%253A%252F%252Fwww.msn.com%252Fde-de%252F%27&-referrerUri=%27%27&-pageTags=%27{\\"pg.t\\"%3A\\"hp\\"%2C\\"pg.p\\"%3A\\"prime\\"%2C\\"pg.c\\"%3A\\"\\"%2C\\"ex\\"%3A\\"\\"%2C\\"rid\\"%3A\\"0e4e9122baae4eb5be694d1c7d2db891\\"%2C\\"clid\\"%3A\\"0672DB74D369646A3C95D40DD2BB6524\\"%2C\\"clidType\\"%3A\\"muid\\"%2C\\"di\\"%3A\\"108\\"%2C\\"partner\\"%3A\\"\\"%2C\\"publcat\\"%3A\\"\\"%2C\\"cvs\\"%3A\\"Browser\\"%2C\\"subcvs\\"%3A\\"homepage\\"%2C\\"entityId\\"%3A\\"\\"%2C\\"entitySrc\\"%3A\\"\\"%2C\\"provid\\"%3A\\"\\"%2C\\"dpt\\"%3A\\"\\"%2C\\"sdpt\\"%3A\\"\\"%2C\\"ar\\"%3A\\"0\\"%2C\\"dgk\\"%3A\\"midlevel.pc.moz\\"%2C\\"imd\\"%3A\\"0\\"%2C\\"parentId\\"%3A\\"\\"%2C\\"pgIdx\\"%3A\\"\\"%2C\\"pgTot\\"%3A\\"\\"%2C\\"anoncknm\\"%3A\\"\\"%2C\\"afd\\"%3A\\"\\"%2C\\"issso\\"%3A\\"0\\"%2C\\"aadState\\"%3A\\"0\\"}%27&-behavior=0&-market=%27de-de%27",
path: "https://web.vortex.data.msn.com/collect/v1/t.gif?name=%27Ms.Webi.PageView%27&ver=%272.1%27&appId=%27JS%3AMSN%27&ext-app-env=%27prod%27&ext-javascript-libver=%274.0.0-beta-10%27&ext-user-localId=%27t%3A0672DB74D369646A3C95D40DD2BB6524%27&*baseType=%27Ms.Content.PageView%27&*isJs=False&*title=%27%27&*isLoggedIn=False&*isManual=True&*serverImpressionGuid=%270e4e9122-baae-4eb5-be69-4d1c7d2db891%27&-ver=%271.0%27&-impressionGuid=%270e4e9122-baae-4eb5-be69-4d1c7d2db891%27&-pageName=%27startpage%27&-uri=%27https%253A%252F%252Fwww.msn.com%252Fde-de%252F%27&-referrerUri=%27%27&-pageTags=%27{\\"pg.t\\"%3A\\"hp\\"%2C\\"pg.p\\"%3A\\"prime\\"%2C\\"pg.c\\"%3A\\"\\"%2C\\"ex\\"%3A\\"\\"%2C\\"rid\\"%3A\\"0e4e9122baae4eb5be694d1c7d2db891\\"%2C\\"clid\\"%3A\\"0672DB74D369646A3C95D40DD2BB6524\\"%2C\\"clidType\\"%3A\\"muid\\"%2C\\"di\\"%3A\\"108\\"%2C\\"partner\\"%3A\\"\\"%2C\\"publcat\\"%3A\\"\\"%2C\\"cvs\\"%3A\\"Browser\\"%2C\\"subcvs\\"%3A\\"homepage\\"%2C\\"entityId\\"%3A\\"\\"%2C\\"entitySrc\\"%3A\\"\\"%2C\\"provid\\"%3A\\"\\"%2C\\"dpt\\"%3A\\"\\"%2C\\"sdpt\\"%3A\\"\\"%2C\\"ar\\"%3A\\"0\\"%2C\\"dgk\\"%3A\\"midlevel.pc.moz\\"%2C\\"imd\\"%3A\\"0\\"%2C\\"parentId\\"%3A\\"\\"%2C\\"pgIdx\\"%3A\\"\\"%2C\\"pgTot\\"%3A\\"\\"%2C\\"anoncknm\\"%3A\\"\\"%2C\\"afd\\"%3A\\"\\"%2C\\"issso\\"%3A\\"0\\"%2C\\"aadState\\"%3A\\"0\\"}%27&-behavior=0&-market=%27de-de%27",
pathFormatted: "req_https---web-vor-dbe7c",
stats: {
    "name": "https://web.vortex.data.msn.com/collect/v1/t.gif?name=%27Ms.Webi.PageView%27&ver=%272.1%27&appId=%27JS%3AMSN%27&ext-app-env=%27prod%27&ext-javascript-libver=%274.0.0-beta-10%27&ext-user-localId=%27t%3A0672DB74D369646A3C95D40DD2BB6524%27&*baseType=%27Ms.Content.PageView%27&*isJs=False&*title=%27%27&*isLoggedIn=False&*isManual=True&*serverImpressionGuid=%270e4e9122-baae-4eb5-be69-4d1c7d2db891%27&-ver=%271.0%27&-impressionGuid=%270e4e9122-baae-4eb5-be69-4d1c7d2db891%27&-pageName=%27startpage%27&-uri=%27https%253A%252F%252Fwww.msn.com%252Fde-de%252F%27&-referrerUri=%27%27&-pageTags=%27{\\"pg.t\\"%3A\\"hp\\"%2C\\"pg.p\\"%3A\\"prime\\"%2C\\"pg.c\\"%3A\\"\\"%2C\\"ex\\"%3A\\"\\"%2C\\"rid\\"%3A\\"0e4e9122baae4eb5be694d1c7d2db891\\"%2C\\"clid\\"%3A\\"0672DB74D369646A3C95D40DD2BB6524\\"%2C\\"clidType\\"%3A\\"muid\\"%2C\\"di\\"%3A\\"108\\"%2C\\"partner\\"%3A\\"\\"%2C\\"publcat\\"%3A\\"\\"%2C\\"cvs\\"%3A\\"Browser\\"%2C\\"subcvs\\"%3A\\"homepage\\"%2C\\"entityId\\"%3A\\"\\"%2C\\"entitySrc\\"%3A\\"\\"%2C\\"provid\\"%3A\\"\\"%2C\\"dpt\\"%3A\\"\\"%2C\\"sdpt\\"%3A\\"\\"%2C\\"ar\\"%3A\\"0\\"%2C\\"dgk\\"%3A\\"midlevel.pc.moz\\"%2C\\"imd\\"%3A\\"0\\"%2C\\"parentId\\"%3A\\"\\"%2C\\"pgIdx\\"%3A\\"\\"%2C\\"pgTot\\"%3A\\"\\"%2C\\"anoncknm\\"%3A\\"\\"%2C\\"afd\\"%3A\\"\\"%2C\\"issso\\"%3A\\"0\\"%2C\\"aadState\\"%3A\\"0\\"}%27&-behavior=0&-market=%27de-de%27",
    "numberOfRequests": {
        "total": "1",
        "ok": "0",
        "ko": "1"
    },
```

**Comment by tomers** [comment] 2020-11-05 20:39
The simulation file that triggers this error:
```
package swg

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._

class SwgBasicProxySimulation extends Simulation {

  val httpProtocol = http
    .inferHtmlResources()
    .nameInferredHtmlResourcesAfterAbsoluteUrl
    .baseUrls(
      "https://msn.com"
    ) // Here is the root for all relative URLs
    .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8") // Here are the common headers
    .doNotTrackHeader("1")
    .acceptLanguageHeader("en-US,en;q=0.5")
    .acceptEncodingHeader("gzip, deflate")
    .userAgentHeader("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0")

  object Browse {
    val browse = exec(
      http("Home")
        .get("/")
    )
    .pause(1)
  }

  val users = scenario("Users").exec(Browse.browse)

  setUp(
    users.inject(
      constantConcurrentUsers({{GATLING_SIMULATION_CONCURRENT_USERS}}) during ({{GATLING_SIMULATION_DURATION}} seconds)
    ).protocols(httpProtocol)
  )
}
```
If this does not produce the error, try to replace `msn.com` with `msn.de`.

**Comment by Isammoc** [comment] 2020-11-05 21:12
quote is not a valid character in URL.

Try with encoding it with `%22`.

Perhaps your browser is showing you that quote, but it transforms it under the hood.

**Comment by tomers** [comment] 2020-11-06 05:45
@Isammoc this is https://msn.com, not my own website. For some reason this invalid character got into the URL of a resource in https://msn.com, and I believe the Gatling tool should be able to cope with such violation.

**Comment by slandelle** [comment] 2020-11-06 09:18
Duplicate of #3998

**Closed by slandelle** 2020-11-06 09:18 UTC
