### ISSUE TITLE
[highcharts] report keeps crashing browser

### ISSUE THREAD

**Issue by manonthemat** [gatling/gatling#2990] opened 2016-04-26 23:32 UTC
For any serious testing scenarios with a larger number of different tests, the resulting report crashes my browser and is not usable to gain any insight.

<img width="1440" alt="screen shot 2016-04-26 at 4 08 09 pm" src="https://cloud.githubusercontent.com/assets/5065940/14837378/85d819aa-0bcc-11e6-8f4e-502e6d118f38.png">

**Comment by slandelle** [comment] 2016-04-27 07:24
Could you share a reproducer, please? How many different request types do you have?

**Comment by manonthemat** [comment] 2016-05-05 17:17
About 25,000 different request types.

**Comment by slandelle** [comment] 2016-05-05 22:33
Definitively not the intended usage.

Closing as "won't fix".

**Closed by slandelle** 2016-05-05 22:33 UTC

**Comment by manonthemat** [comment] 2016-05-05 22:56
What is the intended usage then?

Once I know, I could update the documentation.

**Comment by slandelle** [comment] 2016-05-06 06:35
Get a look at our HTML reports, you'll realize that we generate a table and a menu which both contain one line per request type. It's very likely that your browser is not fond of such huge tables.

Then, I'm not sure why you want to deal with such a humongous number of request types.

**Comment by manonthemat** [comment] 2016-05-06 22:21
I'm aware of how the reports are being generated.

The reason why I want to deal with such a large number of request types is the ability to analyze requests more specifically.

While it's surely overall acceptable to have a general idea on the performance on requests to http://server/content/_:contentId_/detail, it becomes apparent when response times for requesting detailed information for pieces of content have a significant range. It becomes important to know that the content with the content id _abc_ comes back in between 50 to 70 ms, but the request with the content id bcd in the path never ever returns in under 2 s, and will even take up to 30 s. That is important information. We can not simply put everything in the "http://server/content/_:contentId_/detail" request type, but need to differentiate.

"http://server/content/_:contentId_/detail"

becomes
- "http://server/content/abc/detail"
- "http://server/content/bcd/detail"

I totally understand if this does not make sense to you, and are unwilling to put any effort in improving highcharts regarding these points. We'll build our own in-house solution if needed. Luckily parsing the simulation.log is simple enough and gives us all the information we need in order to format the data more suitable for a small front end application.

**Comment by slandelle** [comment] 2016-05-09 15:17
Yes, I think we won't invest on this for Gatling standard reports.
However, we're trying to support this in FrontLine.
