### ISSUE TITLE
Documentation: Little bug in "What's New" order

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4360] opened 2022-12-15 20:55 UTC
It's only appear on main documentation site https://gatling.io/docs/gatling/
I have checked some of other pages and it's look correct but you should check all of them.

![image](https://user-images.githubusercontent.com/30750006/207965083-9764af19-73d8-482e-9e61-a416c2164b38.png)

**Comment by slandelle** [comment] 2022-12-15 23:23
That's a know issue (also happens with the "Upgrading" section). We're still investigating. Looks like a cache refresh issue.

**Comment by gemiusz** [comment] 2022-12-15 23:39
Aditionally in exclamation mark table in "What's New in 3.9" should be information about 3.9 breaking changes (it's about 3.8) and there should be link to correct Upgrade guide - now its to 3.7 to 3.8.

**Comment by slandelle** [comment] 2022-12-16 08:27
Sort order fixed too!

**Comment by gemiusz** [comment] 2022-12-16 08:46
> Sort order fixed too!

When will be online?
I have checked and both (order and inside in what's new) are not fixed :/

**Comment by slandelle** [comment] 2022-12-16 08:48
???
The issue came back?!

**Comment by gemiusz** [comment] 2022-12-16 09:21
Yes, I still see that. 
I have cleared browser cache and try in incognito mode:
![image](https://user-images.githubusercontent.com/30750006/208065613-396907c6-d895-41e5-99b8-fd26d246f995.png)
![image](https://user-images.githubusercontent.com/30750006/208065683-453bd6e0-672b-4fb2-8ef5-b631b17fb022.png)

**Comment by gemiusz** [comment] 2022-12-16 09:25
I tried on mobile phone too using mobile internet and I have the same result.

**Comment by slandelle** [comment] 2022-12-16 09:30
I think the issue is with synchronizing parent pages. But that's for @notdryft to investigate.

**Comment by notdryft** [comment] 2022-12-28 10:52
It was indeed in the synchronization. Should be fixed, will close the issue on confirmation.

**Comment by slandelle** [comment] 2022-12-28 20:03
That's all good now! Thanks a lot!

**Closed by slandelle** 2022-12-28 20:03 UTC
Labels: Type - Bug, Documentation
