### ISSUE TITLE
Gatling users terminate prematurely (supposedly on getting HTTP 5xx)

### ISSUE THREAD

**Issue by EugeneAbramchuk** [gatling/gatling#3336] opened 2017-07-24 11:25 UTC
Hi Stephane et al,

another problem surfaced, which I cannot fully explain.

I have a scenario with two parts: setting up and the load generation, the latter being in the forever loop:

```
override def scenarioBuilder = scenario(getClass.getSimpleName)
    .exec(Account.create)
    .exec(Account.login)
    .exec(Account.activate)
    .exec(Loop.create)
    .forever(
      exec(Log.putEvents)
  ...
)
```

Given the scenario forever loop, the only way for a user to exit prematurely (before the scenario max duration runs out) is either _exitHereIfFailed_ or _exitBlockOnFail_, neither of which are used here.

During the scenario execution the users go down unexpectedly, both being executed locally and on Jenkins.

From the execution log:

> ================================================================================
> 2017-07-24 14:10:56                                          30s elapsed
> ---- Requests ------------------------------------------------------------------
> > Global                                                   (OK=547    KO=2     )
> > account.create                                           (OK=41     KO=0     )
> > account.login                                            (OK=41     KO=0     )
> > account.activate                                         (OK=40     KO=0     )
> > loop.create                                              (OK=39     KO=0     )
> > log.putEvents                                            (OK=194    KO=2     )
> ...
> ---- Errors --------------------------------------------------------------------
> > status.find.is(200), but actually found 504                         2 (100.0%)
> 
> [-------------------------                                                 ]  0%
>           waiting: 100    / active: 50     / done:0     

followed by two users terminating:

> ================================================================================
> 2017-07-24 14:11:01                                          35s elapsed
> ---- Requests ------------------------------------------------------------------
> > Global                                                   (OK=663    KO=4     )
> > account.create                                           (OK=51     KO=0     )
> > account.login                                            (OK=48     KO=0     )
> > account.activate                                         (OK=48     KO=0     )
> > loop.create                                              (OK=47     KO=0     )
> > log.putEvents                                            (OK=235    KO=4     )
> ---- Errors --------------------------------------------------------------------
> > status.find.is(200), but actually found 504                         4 (100.0%)
> 
> [----------------------------                                              ]  1%
>           waiting: 92     / active: 56     / done:2     

For the reference, the log.putEvents method:

```
  val HTTP_OK = status.is(200)

  lazy val putEvents = exec(session => {
      AWSSigner.signAsAdmin(session, REQUEST_BODY)
    })
    .exec(http("log.putEvents")
      .post("/")
      .header("X-QA", QA_HEADER)
      .header("X-Amz-Target", VERSION)
      .header("X-Amz-Date", (session) => session.get("X-Amz-Date").as[String])
      .header("Authorization", (session) => session.get("Authorization").as[String])
      .body(ElFileBody(REQUEST_BODY))
      .asJSON
      .check(HTTP_OK))
```

Do you have any idea what might have been broken? At the moment the best one I have is a suspicion that HTTP 5xx responses could occasionally cause this, as it never happens when there are no errors.

Gatling 2.2.4

**Comment by EugeneAbramchuk** [comment] 2017-07-24 11:31
Image from the previous execution. Scenario duration set to 2400 seconds, actual scenario duration 786 seconds.

<img width="900" alt="screen shot 2017-07-24 at 14 20 12" src="https://user-images.githubusercontent.com/14140360/28521509-b1980986-707c-11e7-86dc-b9fb65404102.png">

**Comment by slandelle** [comment] 2017-07-24 12:15
Could you please provide an actionable reproducer?

**Comment by EugeneAbramchuk** [comment] 2017-07-27 15:28
@slandelle The scenario is as simple as spamming an action (reproduced with POST HTTP requests) which fails with HTTP 504 in a forever loop.

I'm pretty confident there is a strong correlation between the two now, not the amount of KOs and users in Done:

```
================================================================================
2017-07-27 18:25:37                                         115s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=859    KO=80    )
> account.create                                           (OK=859    KO=80    )
---- Errors --------------------------------------------------------------------
> status.find.is(200), but actually found 504                        80 (100.0%)

---- OnboardingDebug -----------------------------------------------------------
[###########################################################---------------] 80%
          waiting: 0      / active: 20     / done:80    
================================================================================
```

The scenario is as simple as

 ```
 override def scenarioBuilder = scenario(getClass.getSimpleName)
    .forever(exec(Account.create))
  override def getRampUpScenario = List(rampUsers(100) over (1 minute))
  override def getMaxDuration = 1500 seconds

```

I could not find any online resource that would deliberately return HTTP 504 to test it out, do you have any ideas?

**Comment by slandelle** [comment] 2017-07-28 07:28
Are you sure you don't have memory issues, and GC eats all CPU?

**Comment by EugeneAbramchuk** [comment] 2017-07-28 15:18
@slandelle tested today - both CPU and memory can be safely ruled out, plenty of free resources even during the peak times. The first user dropouts actually occurred on as low as 15% CPU / 10% RAM used. Is there any way to log user thread shutdown reason?

**Comment by slandelle** [comment] 2017-07-28 16:54
A JVM won't use more memory than allocated, so the system used memory is not meaningful. Typically, you want to know the JVM heap usage. Use a tool such as VisualVM.
From your charts, it really looks like something is eating resources.

**Comment by EugeneAbramchuk** [comment] 2017-07-31 15:24
@slandelle I increased the heap size, but the users keep falling roughly in the same place. Is there any way I can debug output on the Active->Done transition to confirm the out of memory issue? Are the OOM/other error messages gagged or they are logged somewhere?

Appreciate your help!

**Comment by slandelle** [comment] 2017-07-31 15:29
OOM would create a heap dump.
Frankly, no idea what your issue is.
If you can't provide an actionable reproducer (a simulation and application sample that we can run on our side), I'm afraid you're on your own.

**Comment by EugeneAbramchuk** [comment] 2017-08-02 13:16
In light of the new discovery in #3338, the users do die after getting a non-HTTP 200 OK from a load balancer (the "killing" request actually never reaches the service).

I ran a few scenarios locally and monitored memory state with VisualVM, the heap is never close to the max when the users shut down.
<img width="1153" alt="screen shot 2017-08-01 at 15 03 12" src="https://user-images.githubusercontent.com/14140360/28875351-f5c9db66-779d-11e7-9d29-20633e75d562.png">


Unfortunately I could not reproduce it with a mock server, it may have something to do with Amazon's infrastructure (all the requests are proxied through an elastic load balancer)

**Comment by EugeneAbramchuk** [comment] 2017-08-02 14:45
I am playing with different load settings of the test. When I considerably dropped down the load, I experienced a situation when the user got a HTTP 504 and shut down only 2 minutes later. This is the first time I see it. I wonder if simulation log will say more?

https://gist.github.com/EugeneAbramchuk/b388dff960bfb775050114967998d833

**Comment by slandelle** [comment] 2017-08-02 14:58
Sorry, but there's no way we can figure out what happens without a reproducer.
I'm pretty sure you're saturating your ALB.
Closing for now. Please ping if you can provide a reproducer, or want to contract so we can investigate in your environment.

**Closed by slandelle** 2017-08-02 14:58 UTC
