### ISSUE TITLE
Incorrect graph data for Active Users over a long time period

### ISSUE THREAD

**Issue by LilSebastian5000** [gatling/gatling#3470] opened 2018-06-04 14:44 UTC
Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [*] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [*] Check that you can reproduce your issue with latest Gatling version
  * [* ] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [*] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
* Regarding feature requests:
  * [*] Explain your use case, not the implementation you have in mind.

I have a script that should ramp up 5 users in a single second, with a 10 second gap in between, over a 2 hour period. Doing the math out, that should be about 3600 users. 

However, the graph is telling me that only 1 user was ramped up every 10-20 seconds, but ~3300 users were ramped up. 

If there really was only 1 user ramped up every 10-20 seconds like the graph shows, there should only be a max of 720 users ramped, so there is an innacuracy between the graph and the number of users called. Has anyone else ran into a similar issue?

Example call (does nothing for 2 sec to wait for an OAUTH token):
```  
val synchronousScenario = List(
    OAuthRequest.inject(atOnceUsers(1)),
    endpt.inject(nothingFor(2 seconds),
      splitUsers(3600) into (5) over (1 seconds)) separatedBy (10 seconds)));

  // Kicks off the scenario
  setUp(synchronousScenario).protocols(httpConf).maxDuration(2 hours);
```

When I halt the script early after maybe 2 minutes and use Gatling command line to generate a report from the simulation log, the graph actually looks accurate, showing 5 users ramping at once with approx 10 seconds in between, so it seems something weird happens to the graph when it's left uninterrupted for a long period of time.

Gatling version 2.3.0
Scala maven plugin version 3.2.2

**Comment by slandelle** [comment] 2018-06-04 17:39
How do you measure the number of injected users? The reports display the number of active users over time, which is entirely different: https://gatling.io/docs/current/general/reports/#active-users-over-time.

Closing as I think you misunderstood the stats.

Then, if you really found an issue, please provide a reproducer we can action on our side.

**Closed by slandelle** 2018-06-04 17:39 UTC

**Comment by LilSebastian5000** [comment] 2018-06-04 17:46
@slandelle I see the number of injected users in the statistics char that shows 3274 users with OK status.

When looking at the Active Users graph, it shows 1 user under "All Users" when hovering over the peaks. However, if I halt the script early after maybe 5 minutes, it shows 5 users under "All Users" when hovering over each of the peaks. 

Why would this information differ depending on when the script is halted, then?

**Comment by slandelle** [comment] 2018-06-04 17:56
>  I see the number of injected users in the statistics chart that shows 3274 users with OK status.

OK, so the stats in the table are, as column header states, **Requests**, not users.

**Comment by LilSebastian5000** [comment] 2018-06-04 18:01
@slandelle Okay thank you, got it. But why would the graph itself not show 5 users being ramped up at once, unless I halt it early? That doesn't seem like a bug?

Regardless of when the script's execution ends, I'd think the ramped users should be the same...

**Comment by slandelle** [comment] 2018-06-04 18:07
> But why would the graph itself not show 5 users being ramped up at once, unless I halt it early?

Because this stats is not "User arrival rate" (available in FrontLine btw), but "Active users", which is computed as:
```
number_of_users_alive_bucket(n)
- number_of_users_alive_bucket(n-1)
- number_of_users_dead_in_bucket(n-1)
```

The larger the time windows, the larger the buckets (IIRC, we compute 1000 plots by default), which can cause variations.
