### ISSUE TITLE
Gradle plugin: Gradle testFixtures

### ISSUE THREAD

**Issue by pandoras-toolbox** [gatling/gatling#4091] opened 2021-05-10 12:55 UTC
My question refers to the Gatling Gradle plugin, but there it is not possible to create an issue.

It seems that the plugin does not support the testFixtures of Gradle but only main and test folders.

Most of my code of the test framework is inside the testFixtures of the subprojects. When I depend on another subproject from the subproject where Gatling it does not work correctly because it seems that the Gatling plugin does not understand the testFixtures concept of Gradle yet.

Do you understand the problem? Or do you need more in information?

**Comment by pandoras-toolbox** [comment] 2021-05-11 07:51
Actually I do need a solution quickly. It would take too long for me to understand your plugin and to provide a pull request.

So I will move the sources from testFixtures to the main source folders because that will probably work with the Gradle plugin for Gatling.

I might do what you requested after that, I am not sure.

**Comment by pandoras-toolbox** [comment] 2021-05-12 07:03
My problem might not be related to the testFixtures feature of Gradle I now think. Anyway, if it is not supported by the Gatling Gradle plugin it will be an issue for someone who uses testFixtures I believe. The use case is a subproject with Gatling which depends on another Java subproject. While the plugin has "gatlingImplementation" to declare a dependency, it has not gatlingTestImplementation, no gatlingApi and also nothing for testFixtures. I think this is clear that a few things related to dependency configuration are missing in the Gatling Gradle plugin. That Gradle plugin is strange since it manipulates the default source sets, puts a "gatling" folder in between src and java folder. I am not sure if that is required, but that kind of implementation looks that it is not very suitable for compatibility to other things in Gradle, and needs very much plugin maintenance whenever Gradle changes something.

**Comment by eshepelyuk** [comment] 2021-05-19 21:14
@pandoras-toolbox gralde manual contains the solution for your problem 
https://docs.gradle.org/current/userguide/java_testing.html#consuming_test_fixtures_of_another_project


Use `gatling` instead of `testImplementation`

**Comment by slandelle** [comment] 2021-05-20 08:33
@pandoras-toolbox Does @eshepelyuk 's suggestion work for you?
@eshepelyuk Should we close this issue?

**Comment by eshepelyuk** [comment] 2021-05-20 08:35
@slandelle let's wait for user feedback, at least couple of weeks before closing :)
I might be wrong as well since we still don't have reproducible source code to be 100% about the reason.

**Comment by pandoras-toolbox** [comment] 2021-05-20 09:44
I think I declared dependencies on testFixtures like documented, but the devil is in a thousand details which could make it go wrong in a non-trivial situation.

But I gave it another try with declaring: `gatlingImplementation(testFixtures(project(":my-subproject")))`

The code in "subprojects/load-test/src/gatling/java" which I then executed gave an error: "java.lang.ClassNotFoundException: javax.rmi.PortableRemoteObject"

However if I execute the same code in "subprojects/load-test/src/testFixtures/java" with the dependency delaration `testFixturesApi(testFixtures(project(":my-subproject")))` then it works.

I cannot prove that it has to do with the Gatling Gradle plugin. I will implement a less optimal workaround because of this, right now I cannot invest time to analyse it for days with uncertain result. Often eventually I stumble upon the solution, or weeks later it is much easier to find it.

So feel free to close it since the only think I have are suspicions, but I have no proof and no time right now to investigate that further, my workaround will have to be good enough for now.

**Comment by eshepelyuk** [comment] 2021-05-20 09:47
Gatling doesnt support java, simulation location must be `src/gatling/scala`

**Comment by eshepelyuk** [comment] 2021-05-20 09:49
The best way will be to send us the project where bug could be reproduced.
Otherwise, this text based debug could last almost eternally.

**Comment by pandoras-toolbox** [comment] 2021-05-20 10:22
I know that Gatling simulation must be in that "scr/gatling/scala" folder. What I am doing is to generate the requests for the load test automatically, which is programmed in Java. I do not intend to learn Scala in the same way I am familiar with Java. I just want to use the Gatling DSL and not much more of Scala. My idea was to call this request generation from the simulation. But now I will create these requests automatically prior before I start the simulation using the already created requests, because otherwise there will be that error.

**Comment by pandoras-toolbox** [comment] 2021-05-20 10:24
I cannot send you the project because it is not for the public. I might sometime create a project where the issue can be reproduced. But you can close this issue, because I do not know if and when I can do that.

**Comment by eshepelyuk** [comment] 2021-05-20 14:51
Sure, creating "fake" project that mimics your project structure would be excellent to be able to reproduce and fix the issue. Take you time to produce one. Thnx in advance.

**Comment by pandoras-toolbox** [comment] 2022-12-08 14:51
I created a temporary fork to make it reproducible: [gatling-gradle-plugin-demo-java-for-issue-4091](https://github.com/pandoras-toolbox/gatling-gradle-plugin-demo-java-for-issue-4091)

It took me a while to provide it because of several reasons which are not important here.

It does not work to start the tests from command line with: `./gradlew --rerun-tasks clean :load:gatlingRun`
The error is: 
> java.lang.NoClassDefFoundError: testfixtures/UrlProvider

However it works in IntelliJ when starting the main method from the Engine class.

If in ComputerDatabaseSimulation you change it to use `main.UrlProvider.getUrl()` instead then it also works from the command line. The problem is somehow related to **_testFixtures_** as it seems.

I would like to keep that code in **_testFixtures_**. But how can I make it work with Gatling then?

**Comment by pandoras-toolbox** [comment] 2022-12-08 16:38
I see the problem now. But it makes sense that the code which I want to use is inside testFixtures and not inside main sources. The testFixtures have been added to Gradle because they make sense to be used in certain situations.

How about the idea that the Gatling plugin supports the Gradle testFixtures? Then the simulation code would be within `src/gatling/testFixtures` which could access testFixtures from other projects.

**Comment by slandelle** [comment] 2022-12-08 16:42
Frankly, we from Gatling have so many more critical things to tackle that we'll never work on this ourselves.
The only chance this ever happens is that someone contributes it.

**Comment by pandoras-toolbox** [comment] 2022-12-09 08:16
I do not have the skill to contribute that, so I will move the code from testFixtures to source/main.

I am wondering why a plugin at all was required for Gatling simulations to be run? Can it be run without that plugin? And is there an example, because all examples which I have seen use that plugin?

**Comment by slandelle** [comment] 2022-12-30 13:06
Closing for now. Feature request has no traction so far.

**Closed by slandelle** 2022-12-30 13:06 UTC
Labels: Type - Feature, help wanted, Module - Gradle Plugin
