### ISSUE TITLE
Groups don't exit properly when wrapping an exitASAP loop

### ISSUE THREAD

**Issue by jklingelAvid** [gatling/gatling#4192] opened 2022-01-12 14:32 UTC
While migrating our tests to Gatling version 3.7.3 we noticed that we got an error in the logs:
`17045 [gatling-1-2] ERROR io.gatling.core.action.GroupEnd - GroupEnd called but head of stack List() isn't a GroupBlock, please report.`

After investigating we found out that it might be related to #4188 

We were able to build a small reproducer:

```
import io.gatling.core.Predef._
import io.gatling.http.Predef._

import scala.concurrent.duration.{FiniteDuration, MINUTES, SECONDS}

class Reproducer extends Simulation {

  val loopCounterKey = "loopCounter"

  def httpConf = http.baseUrl("https://httpbin.org")

  def testScenario = scenario("Test Scenario")
    .exec(session => session.set(loopCounterKey, 0))
    .group("Test group") {
      doWhileDuring(session => session(loopCounterKey).as[Int] < 5, FiniteDuration(1, MINUTES)) {
        exec(http("Test GET")
          .get("https://httpbin.org/status/200")
          .check(status.is(200)))
          .exec(session => session.set(loopCounterKey, session(loopCounterKey).as[Int] + 1))
          .pause(FiniteDuration(2, SECONDS))
      }
    }


  setUp(
    testScenario.inject(
      atOnceUsers(1)
    ).protocols(httpConf)
  )

}
```

When the loop finishes the above error is logged and the simulation will hang.

**Comment by slandelle** [comment] 2022-01-12 14:45
It's a duplicate of #4188. Please revert to 3.7.2 until we release 3.7.4.

**Closed by slandelle** 2022-01-12 14:45 UTC
