### ISSUE TITLE
Cheat Sheet CSS broken

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#2948] opened 2016-03-17 09:07 UTC
Hello guys,

for some amount of times now, the Cheat Sheet CSS is broken.
See http://gatling.io/docs/2.1.7/cheat-sheet.html

**Comment by notdryft** [comment] 2016-03-17 09:19
This is a broken link, the real url is here:
http://gatling.io/#/cheat-sheet/2.1.7

Where did you find this one so we can change it?

**Comment by mxbossard** [comment] 2016-03-17 09:38
My bad, I found it in google :p 
https://www.google.fr/webhp?hl=fr#hl=fr&q=cheat+sheet+gatling

**Comment by notdryft** [comment] 2016-03-17 09:56
Not really your fault :)

I'll mark this as a duplicate of #2878.

**Closed** 2016-03-17 09:56 UTC
