### ISSUE TITLE
Core: exitHere in tryMax - should Exit and not report Requests

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4325] opened 2022-09-05 13:48 UTC
Gatling: 3.8.3
OS: Windows 10 Pro
JDK: jdk-17.0.4

I'm not sure if this is a bug and can be associated with [#4324](https://github.com/gatling/gatling/issues/4324)
When using exitHere in tryMax, User should exit the scenario from this point and not raport information about this requests.
I

Scenario:
```
public class ExitHereStatusCodeSimulation extends Simulation {

    HttpProtocolBuilder httpProtocol =
            http
                    .baseUrl("https://postman-echo.com");

    ScenarioBuilder scn =
            scenario("GeMi_ExitHereStatusCodeSimulation")
                    .tryMax(5, "counter").on(
                            doIfEquals("#{counter}", 2).then(
                                            exitHere()
                                    ).
                                    exec(
                                            http("GeMi_ExitHereStatusCodeSimulation_get")
                                                    .get("/status/414")
                                    ));

    {
        setUp(scn.injectOpen(atOnceUsers(1)).protocols(httpProtocol));
    }
}
```

**Comment by Isammoc** [comment] 2022-09-05 14:46
Why no report for this request? There were a executed request that have failed.
2 requests (`counter = 0` and `counter = 1`) were run, and failed (414 is an error status)
The third execution of the body, `counter = 2` and the user should exit here.

What do you see ? a third execution of the request?

**Comment by gemiusz** [comment] 2022-09-05 14:53
Main case is how **tryMax** should work - therefore I made a link to case #4324.
As I understood **tryMax** should be as some "internal try until positive result or until last negative call" so if there aren't "positive/last negative" there shouldn't be any information about this request.

**Comment by gemiusz** [comment] 2022-09-05 14:55
If you wondering why I want to use it in this way please look at [https://community.gatling.io/t/how-to-handle-multiple-responses-from-server/7118/2](https://community.gatling.io/t/how-to-handle-multiple-responses-from-server/7118/2)

**Comment by slandelle** [comment] 2022-09-05 15:57
Closing as a duplicate of #4324. `tryMax` doesn't silently discard failed requests.

**Closed by slandelle** 2022-09-05 15:57 UTC
