### ISSUE TITLE
assertions.json is not produced anymore - only assertions.xml

### ISSUE THREAD

**Issue by bw-interhyp** [gatling/gatling#4506] opened 2024-01-03 13:42 UTC
With latest gatling update the assertions.json is missing in report folder. I'm using this configuration:
``` 
# Plugins
javaVersion=17
gatlingPluginVersion=3.10.3

# Dependencies
gatlingVersion=3.10.3

**Comment by slandelle** [comment] 2024-01-03 13:48
Duplicate of #4500

**Closed by slandelle** 2024-01-03 13:48 UTC
