### ISSUE TITLE
org.slf4j.helpers.NOPLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext

### ISSUE THREAD

**Issue by ThomasVuillaume** [gatling/gatling#3291] opened 2017-04-26 09:29 UTC
Good morning everyone,

I'm currently trying the latest Gatling version (gatling-charts-highcharts-bundle-2.2.5) on Windows 7 Pro (SP1) 64 bits.

When I launch a simultation, everything goes well, and the report is generated, but at the very last moment, when Gatling is exitting, I got this:

```java
Exception in thread "main" java.lang.ClassCastException: org.slf4j.helpers.NOPLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
        at io.gatling.app.Gatling$.start(Gatling.scala:66)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:43)
        at io.gatling.app.Gatling$.main(Gatling.scala:35)
        at io.gatling.app.Gatling.main(Gatling.scala)
```

**Comment by slandelle** [comment] 2017-04-26 09:36
Duplicate of #3290

**Closed by slandelle** 2017-04-26 09:36 UTC
