### ISSUE TITLE
SSE test will hang when connection reached around 1024

### ISSUE THREAD

**Issue by zhudaxi** [gatling/gatling#3658] opened 2019-01-25 16:44 UTC
In Gatling 3.0.2, we are using testing an easy SSE connection case, and found that when the SSE connection reached 1024 for single user, the test will hang. For multi-user test, the test hangs when SSE connection a little higher than 1024 (e.g. 1029, 1034).

Our script is like below:
`val scn = scenario("sse_test").during(100 seconds)`
`{`
`	exec(http("create session").post("/createSessionAPI")
	.check(jsonPath("$..session").saveAs("my_session"),jsonPath("$..message").saveAs("my_response")))
	.doIfEquals("${my_response}","Session has been created.")`
`    {`
  ` exec(sse("Get SSE").connect("/createSSE/${my_session}")
   .await(30 seconds)(sse.checkMessage("checkResponse").check(substring("hhhh"))))
   .exec(sse("Close sse").close())`
`   }`
`}`

Attached is the output when test hangs with 1 user and SSE reached 1024 connections.
[Output.txt](https://github.com/gatling/gatling/files/2796981/Output.txt)

**Comment by slandelle** [comment] 2019-01-25 21:01
How can you be sure that it's not your server that stops sending messages?
Please provide a reproducer we can run on our side.

**Comment by zhudaxi** [comment] 2019-01-25 23:51
Thanks for your quick response. That's a good point, we can further investigate.

Another interesting thing we found:
We checked the server side log, and find that when calling "close sse", the server side received a same api call as "open sse", but with a different client id. Is this behavior expected? Thanks!

**Comment by slandelle** [comment] 2019-01-26 08:12
> We checked the server side log, and find that when calling "close sse", the server side received a same api call as "open sse", but with a different client id. Is this behavior expected? Thanks!

No, that's absolutely not what happens. `close` merely closed the socket. Then, your `during` loop kicks in and you create an new "session" and open a new stream.

My2cents: you're not destroying your "session" when the stream is closed and they pile up in memory.

Closing for now as it looks like an application issue and Gatling is merely the messenger.
Feel free to ping if you can provide a reproducer that demonstrate the issue is on the Gatling side.

**Closed by slandelle** 2019-01-26 08:12 UTC
Labels: Waiting for User
