### ISSUE TITLE
Broken sorting by rps, KO and KO% in HTML reports

### ISSUE THREAD

**Issue by MaksSieve** [gatling/gatling#3697] opened 2019-04-04 06:13 UTC
Sorting by rps, KO and KO% in a report works incorrect in Gatling 3.0.3. It changes only a piece of rows, but others are on their places.
Examples:
![image](https://user-images.githubusercontent.com/9395027/55533353-b230ec80-56b9-11e9-9f23-3ce1d31b23f5.png)

![image](https://user-images.githubusercontent.com/9395027/55533377-c70d8000-56b9-11e9-9e45-8688595b259a.png)

**Comment by slandelle** [comment] 2019-04-04 06:45
Can’t reproduce. Could you please share your simulation.log file and your browser version?

**Comment by slandelle** [comment] 2019-04-05 11:47
@MaksSieve Gentle ping. We plan on releasing 3.1.0 next week, so if there's indeed a bug, we'd like to be able to fix it by then.

**Comment by slandelle** [comment] 2019-05-06 12:40
Can't reproduce. No update from user. Closing for now, will reopen if we get more information.

**Closed by slandelle** 2019-05-06 12:40 UTC
