### ISSUE TITLE
bodyBytes comparison against RawFileBody always fails

### ISSUE THREAD

**Issue by pmalic** [gatling/gatling#3705] opened 2019-04-11 18:50 UTC
When "Save & check response bodies?" is turned on in Recorder, the generated code uses bodyBytes to check against RawFileBody, e.g:
```scala
.check(bodyBytes.is(RawFileBody("test_0028_response.txt"))))
```

This check always fails with the following error:
```
bodyBytes.find.is([B@2f6a5e1), found [B@3286f99b
```

I've tried 3.0.3 and several older versions. The furthest I went back is 2.2.0 but this version generates code that doesn't compile (uses bodyString against RawFileBody).

If I change the code to following:
```scala
.check(bodyString.is(ElFileBody("test_0029_response.txt")))
```
Then it works for non-binary files but of course fails for binary files like images.

**Comment by slandelle** [comment] 2019-04-11 18:55
Duplicate of #3631

**Closed by slandelle** 2019-04-11 18:55 UTC

**Comment by pmalic** [comment] 2019-04-11 19:20
Sorry for the duplicate, I did look for existing issues, but was searching for RawFileBody.

**Comment by slandelle** [comment] 2019-04-11 19:22
No pro, it was far from obvious :)
Next release will be out beginning of next week.
