### ISSUE TITLE
HTTP: Connection crash during SSL renegociation

### ISSUE THREAD

**Issue by crazyvan25** [gatling/gatling#4120] opened 2021-07-27 13:27 UTC
Hi, I've just upgraded to 3.6.1 and one of my scenarios is failing.

A minimal example:

```package account.info

import io.gatling.core.Predef._
import io.gatling.http.Predef.http

import scala.concurrent.duration._

class TokenInfoSimulation extends Simulation {

  private val baseProtocol = http
    .userAgentHeader("Gatling")
    .acceptEncodingHeader("gzip,deflate")

  private val tokenInfoScenario =
    scenario("Token Info")
      .exec(
        http("Token Info")
          .get("https://access.stage.api.bbc.com/v1/user/tokenInfo")
      )

  setUp(
    tokenInfoScenario
      .inject(
        constantUsersPerSec(5) during (10 seconds)
      )
      .protocols(baseProtocol)
  )

}
```

All of the requests fail with:

---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=50    )
> Token Info                                               (OK=0      KO=50    )
---- Errors --------------------------------------------------------------------
> j.i.IOException: Premature close                                   50 (100.0%)

I have the following in my `build.sbt`:

```
libraryDependencies += "io.gatling.highcharts" % "gatling-charts-highcharts" % "3.6.1" % "test"
libraryDependencies += "io.gatling" % "gatling-test-framework" % "3.6.1" % "test"
```

**Comment by slandelle** [comment] 2021-07-27 13:42
Looks like a bug in netty's BoringSSL. Thanks for reporting.
In the meantime, please set `useOpenSsl` to `false` in `gatling.conf`.

**Comment by slandelle** [comment] 2021-07-27 15:42
I still can't figure out the conditions that trigger the issue exactly, but it looks like the server chokes because of the `Host` header (here, it's set to `access.stage.api.bbc.com`). Does it ring a bell? Any chance you might have something misconfigured on your side?

**Comment by slandelle** [comment] 2021-07-27 15:51
Inspecting packets with WireShark, it looks like your server is sending an extra "Encrypted Handshake Message" **after** the end of the handshake and the client as sent the request. This causes the client SSLEngine to crash and the connection to get closed.
It looks like a server error to me.

**Comment by crazyvan25** [comment] 2021-07-28 18:39
Thanks for looking into this, you were on the right path :)
I decrypted the `Encrypted Handshake Message` and it is a `Hello Request`.
We use Apache reverse proxy with client certificate authentication enabled in per-directory context:
``` 
<Location "/v1/user/tokenInfo">
        SSLVerifyClient optional_no_ca
</Location>
```
From the Apache docs:
In per-directory context it forces a SSL renegotiation with the reconfigured client verification level after the HTTP request was read but before the HTTP response is sent.

This is my understanding of the above:
- the first negotiation happens (without client auth)
- client sends Application Data (HTTP request)
- Apache checks URL and decides whether it needs to do client cert authentication; if it does, it triggers a renegotiation by sending the `Hello Request` (client is expected to send a `Client Hello` after this, at least according to https://datatracker.ietf.org/doc/html/rfc5246#section-7.4.1.1)
- during the 2nd handshake Apache sends a `Certificate Request` and then performs cert validations based on what's inside the directive.

Postman uses BoringSSL since v7.25.1 and handles this case correctly (I'm using 8.8.0). Wireshark shows that it renegotiates sucessfully, whereas the version used in Gatling sends an `Encrypted Alert` (close_notify) immediately after the `Hello Request`.

**Comment by slandelle** [comment] 2021-07-29 16:48
Thanks for the details. I've opened an issue against Netty.

**Comment by slandelle** [comment] 2021-08-05 19:57
It turns out we have to implement a way to enable renegociation in BoringSSL (it's disabled by default as it's considered a flawed unsecure mechanism) through Netty components.

This will take some time.

In the meantime, please disable BoringSSL for this use case.

**Comment by slandelle** [comment] 2021-08-23 11:56
This will be fixed as of Netty 4.1.68.

**Closed** 2021-09-23 14:52 UTC
Labels: Module - HTTP, Type - Bug

**Comment by slandelle** [comment] 2022-03-08 15:38
@crazyvan25 reproducer please?

**Comment by crazyvan25** [comment] 2022-03-08 16:35
It's the same scenario I originally shared here: https://github.com/gatling/gatling/issues/4120#issue-953884750

**Comment by slandelle** [comment] 2022-03-08 16:46
It no longer works for me. Even a browser can send a request to `https://access.stage.api.bbc.com/v1/user/tokenInfo`. I think I need the new IP address.

**Comment by crazyvan25** [comment] 2022-03-08 16:56
Apologies, I took the server out earlier; it's back up again.

**Comment by slandelle** [comment] 2022-03-08 19:29
On my end, either with a browser or with Gatling, I get the same response:

```
================================================================================
---- Global Information --------------------------------------------------------
> request count                                          1 (OK=0      KO=1     )
> min response time                                    656 (OK=-      KO=656   )
> max response time                                    656 (OK=-      KO=656   )
> mean response time                                   656 (OK=-      KO=656   )
> std deviation                                          0 (OK=-      KO=0     )
> response time 50th percentile                        656 (OK=-      KO=656   )
> response time 75th percentile                        656 (OK=-      KO=656   )
> response time 95th percentile                        656 (OK=-      KO=656   )
> response time 99th percentile                        656 (OK=-      KO=656   )
> mean requests/sec                                      1 (OK=-      KO=1     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             0 (  0%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            0 (  0%)
> failed                                                 1 (100%)
---- Errors --------------------------------------------------------------------
> status.find.in([200, 209], 304), found 400                          1 (100.0%)
================================================================================
```

```
400 Bad Request
{"code":"REQUIRED","failedValidation":true,"path":["paths","/v1/user/tokenInfo","get","parameters","1"],"paramName":"authorization","errorCode":400,"description":"Request validation failed: Parameter (authorization) is required"}
```

Also, note that your certificate is invalid because the root CA can't be trusted.

So, works as expected.

**Comment by crazyvan25** [comment] 2022-03-09 11:45
Sorry, I missed a few things out which are important.

Firstly, in build.sbt I have version `3.7.5`:

```
libraryDependencies += "io.gatling.highcharts" % "gatling-charts-highcharts" % "3.7.5" % "test"
libraryDependencies += "io.gatling" % "gatling-test-framework" % "3.7.5" % "test"
```

In `gatling.conf` in the `ssl` section, I've supplied a self-signed cert:

```
ssl {
    useOpenSsl = true                  # if OpenSSL should be used instead of JSSE (only the latter can be debugged with -Djava.net.debug=ssl)
    #useOpenSslFinalizers = false         # if OpenSSL contexts should be freed with Finalizer or if using RefCounted is fine
    #handshakeTimeout = 10000             # TLS handshake timeout in millis
    #useInsecureTrustManager = true       # Use an insecure TrustManager that trusts all server certificates
    #enabledProtocols = []             # Array of enabled protocols for HTTPS, if empty use Netty's defaults
    #enabledCipherSuites = []          # Array of enabled cipher suites for HTTPS, if empty enable all available ciphers
    #sessionCacheSize = 0              # SSLSession cache size, set to 0 to use JDK's default
    #sessionTimeout = 0                # SSLSession timeout in seconds, set to 0 to use JDK's default (24h)
    #enableSni = true                     # When set to true, enable Server Name indication (SNI)
    keyStore {
      type = "PKCS12"      # Type of SSLContext's KeyManagers store
      file = "/Users/user/Desktop/mycert.p12"      # Location of SSLContext's KeyManagers store
      password = "test1234"  # Password for SSLContext's KeyManagers store
      #algorithm = "" # Algorithm used SSLContext's KeyManagers store
    }
    trustStore {
      #type = ""      # Type of SSLContext's TrustManagers store
      #file = ""      # Location of SSLContext's TrustManagers store
      #password = ""  # Password for SSLContext's TrustManagers store
      #algorithm = "" # Algorithm used by SSLContext's TrustManagers store
    }
  }
```

To create `mycert.p12`:
```bash
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj /CN=myhost.com
openssl pkcs12 -export -in cert.pem -inkey key.pem -out mycert.p12 -name "my cert"
```

When I set `useOpenSsl` to `false`, the simulation fails with (which is expected as the `authorization` header is missing):
---- Errors --------------------------------------------------------------------
> status.find.in([200, 209], 304), found 400                          1 (100.0%)

Wireshark shows:
<img width="873" alt="Screenshot 2022-03-09 at 11 32 18" src="https://user-images.githubusercontent.com/59562991/157433700-a78237dc-57fe-4d3a-911f-82566d25d92e.png">

When I set `useOpenSsl` to `true`, the simulation fails with:
---- Errors --------------------------------------------------------------------
> j.i.IOException: Premature close                                    1 (100.0%)

Wireshark shows:
<img width="732" alt="Screenshot 2022-03-09 at 11 38 53" src="https://user-images.githubusercontent.com/59562991/157434765-bcd674f7-6e48-4bb1-ad6f-c0cf65aa2589.png">


I've also repro-ed this with a valid client cert that is trusted by the server and the behaviour is similar.
