### ISSUE TITLE
incrementUsersPerSec putting load on the system in reverse (starting with high load and decrementing)

### ISSUE THREAD

**Issue by prasadvankayala** [gatling/gatling#3823] opened 2019-11-07 22:15 UTC
Make sure these checkboxes are checked before submitting your issue. Thanks you!

* [ ] Don't post questions here. This bugtracker is for issues and feature requests only. Use the [community mailing list](https://groups.google.com/forum/#!forum/gatling) instead.
* Regarding issues:
  * [*] Check that you can reproduce your issue with latest Gatling version
  * [ ] Search this bugtracker for any similar issue that might have already been reported (and possibly fixed and available as a SNAPSHOT version)
  * [*] Provide a way for Gatling developers to reproduce your problem, e.g. step-by-step instructions against a public facing website, or a sample application that demonstrates your problem.
- Create a simulation using incrementUsersPerSec
Here's my code :
incrementUsersPerSec(inc) //inc represents step tps to increment by how much
     .times(numSteps)
      .eachLevelLasting(rampTime minutes)
       .separatedByRampsLasting(rampTime minutes)
      .startingFrom(0)

This is putting the load in reverse order for example ::
inc = 2 tps, numSteps =5, rampTime = 2 minutes

The load level starts with 10 tps and going down by 2 tps each step rather than starting at 2 tps and increments to 10 tps
This is run in Gatling Frontline as well as local gatling setup and in both instances it shows the same.

* Regarding feature requests:
  * [ ] Explain your use case, not the implementation you have in mind.

**Comment by slandelle** [comment] 2019-11-08 08:16
Duplicate of #3818, was fixed in 3.3.1.

**Closed by slandelle** 2019-11-08 08:16 UTC
