### ISSUE TITLE
Getting compilation error for HAR file of secured website

### ISSUE THREAD

**Issue by rgupta95** [gatling/gatling#4238] opened 2022-04-28 12:14 UTC
I am getting below compilation error while running the gatling.bat file for HAR file which i imported for secured website.
 C:/Users/ranjan.gupta/Documents/automationStuffs/Gatling/gatling-charts-highcharts-bundle-3.7.6/user-files/simulatio
ns/MyComputerTest.scala:209:13: identifier expected but '.' found.
            .headers(headers_2),
            ^
04:53:58.928 [ERROR] i.g.c.ZincCompiler$ - C:/Users/ranjan.gupta/Documents/automationStuffs/Gatling/gatling-charts-highcharts-bundle-3.7.6/user-files/simulatio
ns/MyComputerTest.scala:421:1: ')' expected but '}' found.
}
^
04:53:58.980 [ERROR] i.g.c.ZincCompiler$ - two errors found
04:53:58.991 [ERROR] i.g.c.ZincCompiler$ - Compilation crashed
xsbt.InterfaceCompileFailed: null
        at xsbt.CachedCompiler0.handleErrors(CompilerBridge.scala:183)
        at xsbt.CachedCompiler0.run(CompilerBridge.scala:172)
        at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
        at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
        at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
        at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
        at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
        at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
        at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
        at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
        at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:177)
        at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:175)
        at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:461)
        at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
        at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
        at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
        at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
        at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:416)
        at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:503)
        at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:403)
        at sbt.internal.inc.Incremental$.apply(Incremental.scala:169)
        at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
        at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
        ... 5 common frames omitted
Wrapped by: sbt.internal.inc.CompileFailed: Compilation failed
        at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:335)
        at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
        at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
        at io.gatling.compiler.ZincCompiler$.doCompile(ZincCompiler.scala:218)
        at io.gatling.compiler.ZincCompiler$.main(ZincCompiler.scala:226)
        at io.gatling.compiler.ZincCompiler.main(ZincCompiler.scala)

Please suggest what to do in this case ? May i assume that Gatling does not support running https site ? 
Thanks!

**Comment by Isammoc** [comment] 2022-04-28 12:17
This is a bug tracker.
For question, please use our [community forum](https://community.gatling.io/)

**Comment by slandelle** [comment] 2022-04-28 12:51
Please provide your HAR file so we can reproduce on our side.

**Comment by slandelle** [comment] 2022-04-29 10:49
Feel free to redact the hostnames, we don't need them.

**Comment by slandelle** [comment] 2022-05-03 11:53
@rgupta95 Gentle ping.

**Comment by slandelle** [comment] 2022-05-18 11:29
Closing due to lack of answer from the user.
Feel free to reach out with the request information so we can reopen.

**Closed by slandelle** 2022-05-18 11:29 UTC
