### ISSUE TITLE
HTTP: Testing hanging on websocket crash

### ISSUE THREAD

**Issue by bromanov** [gatling/gatling#2601] opened 2015-03-07 05:06 UTC
Hi, i'm trying to run benchmark against socket.io apllication. Sometimes server closes websocket unappropriately and after that test is unable to finish. |t hangs like this:

```
20:52:18.558 [New I/O worker #15] DEBUG c.n.h.c.p.netty.handler.Processor - Unexpected I/O exception on channel [id: 0x3b965152, /127.0.0.1:8883 => local.talkto.io/127.0.0.1:9999]
java.io.IOException: Connection reset by peer
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_60]
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.7.0_60]
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.7.0_60]
    at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.7.0_60]
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.7.0_60]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64) [netty-3.10.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.0.Final.jar:na]
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.0.Final.jar:na]
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.0.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_60]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_60]
20:52:18.558 [GatlingSystem-akka.actor.default-dispatcher-9] DEBUG o.j.n.h.c.h.w.WebSocket08FrameEncoder - Encoding WebSocket Frame opCode=1 length=278
20:52:18.558 [New I/O worker #15] DEBUG c.n.h.c.p.netty.handler.Processor - Trying to recover from dead Channel: [id: 0x3b965152, /127.0.0.1:8883 => local.talkto.io/127.0.0.1:9999]
20:52:18.558 [New I/O worker #15] DEBUG c.n.h.c.p.netty.handler.Processor - Channel Closed: [id: 0x3b965152, /127.0.0.1:8883 :> local.talkto.io/127.0.0.1:9999] with attribute NettyResponseFuture{currentRetry=0,
    isDone=true,
    isCancelled=false,
    asyncHandler=com.ning.http.client.ws.WebSocketUpgradeHandler@42fa8686,
    nettyRequest=com.ning.http.client.providers.netty.request.NettyRequest@4d95e9c4,
    content=NettyWebSocket{channel=[id: 0x3b965152, /127.0.0.1:8883 :> local.talkto.io/127.0.0.1:9999]},
    uri=ws://local.talkto.io:9999/socket.io/1/websocket/883c2296-8253-4c3c-a2b6-6789960b4aa8,
    keepAlive=true,
    httpHeaders=org.jboss.netty.handler.codec.http.DefaultHttpHeaders@2d266aa7,
    exEx=null,
    redirectCount=0,
    timeoutsHolder=null,
    inAuth=false,
    statusReceived=false,
    touch=1425703938558}
20:52:18.559 [New I/O worker #15] DEBUG c.n.h.c.p.n.channel.ChannelManager - Closing Channel [id: 0x3b965152, /127.0.0.1:8883 :> local.talkto.io/127.0.0.1:9999] 
20:52:18.559 [GatlingSystem-akka.actor.default-dispatcher-9] DEBUG io.gatling.http.action.ws.WsActor - Websocket 'gatling.http.webSocket' closed by the server
```

```
================================================================================
2015-03-06 21:06:08                                        1140s elapsed
---- WebSocket -----------------------------------------------------------------
[#############################---------------------------------------------] 40%
          waiting: 0      / active: 6      / done:4     
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=274    KO=44    )
> Socket Id                                                (OK=10     KO=0     )
> Connect WS                                               (OK=10     KO=0     )
> INIT WS                                                  (OK=10     KO=0     )
> INIT WS Check                                            (OK=10     KO=0     )
> Heartbeat                                                (OK=132    KO=0     )
> Say Hello WS                                             (OK=71     KO=0     )
> Say Hello WS Check                                       (OK=27     KO=44    )
> Socket close                                             (OK=4      KO=0     )
---- Errors --------------------------------------------------------------------
> Check failed: Timeout                                              38 (86.36%)
> Websocket 'gatling.http.webSocket' was unexpectedly closed wit      6 (13.64%)
h status 1006 and message Connection was closed abnormally (th...
================================================================================
```

**Comment by slandelle** [comment] 2015-03-08 21:22
@bromanov Thanks for reporting!

I think the problem is that pending checks are not honored in case of a connection crash: https://github.com/gatling/gatling/blob/v2.1.4/gatling-http/src/main/scala/io/gatling/http/action/ws/WsActor.scala#L281

Will fix.

**Comment by slandelle** [comment] 2015-03-25 16:21
We're getting lost in there, so we're reimplementing the Ws stuff on top of FSM. But this will happen in 2.2.0. I'm afraid this issue will have to wait until then.

**Comment by maxdemarzi** [comment] 2015-06-26 08:33
Any luck with this one? I'm getting this on 2.2.0-M3 using `wsAwait`, with `wsListen` I get `Check didn't succeed by the time a new one was set up` instead. 

```
================================================================================
2015-06-26 03:06:55                                          25s elapsed
---- Get Document WebSocket ----------------------------------------------------
[#####################################-------------------------------------] 50%
          waiting: 0      / active: 1      / done:1     
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=12     KO=1     )
> Connect WS                                               (OK=2      KO=0     )
> get document websocket                                   (OK=5      KO=0     )
> get document websocket Check                             (OK=4      KO=1     )
> Close WS                                                 (OK=1      KO=0     )
---- Errors --------------------------------------------------------------------
> Websocket 'gatling.http.webSocket' was unexpectedly closed wit      1 (100.0%)
h status 1006 and message Connection was closed abnormally (th...
================================================================================
```

**Comment by slandelle** [comment] 2015-06-26 08:44
Hi @maxdemarzi 

The issue is with the test hanging. But the message is "Connection was closed abnormally (that is, with no close frame being sent)." really explains what happens. You should investigate why your server/websocket implementation behaves in such an improper manner.

Regarding the core issue, no, we haven't make any progress on it. Low priority atm.

**Comment by attack7** [comment] 2015-06-30 02:07
Thanks for working on this slandelle.  Gatling is helping us verify our websocket configuration, and any improvements here will really help us out!

**Comment by slandelle** [comment] 2015-06-30 09:17
@attack7 Sorry, but atm I have to give priority to what pays the bills. If you're in a hurry, please consider contributing or getting a support contract.

**Comment by SlavikCA** [comment] 2015-08-20 19:52
I added "bounty" for this bug:
https://www.upwork.com/o/jobs/job/Fix-WebSocket-bug-Gatling-project_~01ffa0f6bde54cbf53/

**Comment by jbank** [comment] 2015-12-11 02:18
I have had a poke around to try and see how this issue can be resolved. I can see that it sets the session to KO and resets the internal state of the websocket actor to the open state.

So it seems that there are a few possibilities here with web sockets
1 - someone else is responsible for checking that sessions have KO'd and restarting them
2 - when the actor becomes KO'd they just stop the actor and who ever is the supervisor is knows what to do with them
3 - a connection timeout isn't a KO and is something that can be recovered from

I am assuming that #3 is just plain wrong. #1 or #2 are reasonable but depend on the overall design principles of gatling. Can you please advise which direction makes the most sense to you?

Jesse

**Comment by sergigp** [comment] 2016-04-29 14:28
Hi,
I'm having the same issue on 2.1.7.

I'm testing the deploy. I have two servers behind an ELB and deploy switches from one machine to another, so the errors are expected (by now) but it should be a nice thing if I can see the report.

> > Couldn't fetch open websocket: No attribute named 'gatling.htt   5389 (20,53%)
> p.webSocket' is defined
> > Check failed: Timeout                                            5358 (20,41%)
> > Websocket 'gatling.http.webSocket' was unexpectedly closed wit    625 ( 2,38%)
> h status 1000 and message
> > Invalid Status Code 0                                             468 ( 1,78%)
> > Websocket 'gatling.http.webSocket' was unexpectedly closed wit      1 ( 0,00%)
> h status 1006 and message Connection was closed abnormally (th...

From what I see, it's not fixed yet in 2.2.0 isn't it?

Regards and thank you for your work with this awesome tool guys.

Sergi

**Comment by slandelle** [comment] 2016-04-29 22:12
No, we haven't worked on this in 2.2. If someone could provide an application that we could test against and reproduce, it would definitively help.

**Comment by slandelle** [comment] 2016-05-16 22:29
It looks like we're ignoring `CheckTimeout` messages while in `disconnected` and `reconnecting` state.

**Comment by aomelchenko** [comment] 2017-03-23 15:24
Hello, any updates on this issue?

**Comment by amyalenkov** [comment] 2017-06-15 14:39
The same behavior in 2.2.5 :(

**Comment by slandelle** [comment] 2017-10-16 13:10
Closing as fixed in master with WebSocket support reboot

**Closed by slandelle** 2017-10-16 13:10 UTC
Labels: Module - HTTP, Type - Bug

**Comment by sergigp** [comment] 2017-12-20 13:03
@slandelle hi and thank you for fixing this. Is the fix included in 2.3 or it will be released in 3.0 ?

Regards

**Comment by slandelle** [comment] 2017-12-20 13:08
The fix is only included in the revamping of the WebSocket support that's happening in 3.0 (see Ws2CompileTest in master). The implementation in 2.x was too complex to fix.

**Comment by camhart** [comment] 2018-01-23 01:51
@slandelle Do we know the state of 3.0?  Any ballpark release dates floating around?

**Comment by slandelle** [comment] 2018-01-23 12:42
@camhart No ETA atm, we still have to tackle HTTP/2 support, finish WebSocket support revamping and support closed workload models.

**Comment by valsaraj** [comment] 2020-08-14 10:00
I am facing issue with session on WildFly-16 & Gatling-3.1.0.1
It's working fine on WildFly-8.2.1. One difference is that later WildFly added support for HTTP/2.
Any workaround for this issue?

**Comment by slandelle** [comment] 2020-08-14 11:12
Please stop spamming unrelated issue. You’ve already asked on the community mailing list and got the best possible answer for the lack of information you provided.
