### ISSUE TITLE
Maven plugin : logback ignored

### ISSUE THREAD

**Issue by kemuning** [gatling/gatling#3210] opened 2016-12-13 13:02 UTC
It seems to me that when invoking gatlin via maven, i.e.:
`mvn clean gatling:execute`
the logback.xml is purely & simply ignored. Just try by changing logback.xml into a not well form XML structure, nothing happen.

**Comment by slandelle** [comment] 2016-12-13 13:35
Sorry, I can't reproduce.
I cloned our [demo](https://github.com/gatling/gatling-maven-plugin-demo), renames `logback-test.xml` into `logback.xml`. Changing logging level to DEBUG or INFO does work.

Closing for now, as I suspect the problem is on your side.
Please feel free to provide a reproducer and I'll reopen.

**Closed by slandelle** 2016-12-13 13:35 UTC

**Comment by kemuning** [comment] 2016-12-13 13:59
True, just cloned downloaded the demo. Thanks.
