### ISSUE TITLE
Support resolution of optional env variables in typesafe config

### ISSUE THREAD

**Issue by denvazh** [gatling/gatling#2622] opened 2015-03-17 15:53 UTC
Using the most recent Gatling version 2.1.4 with gatling-sat plugin I found, that it is not possible to use optional environment variables in custom configuration file.

For example configuration like below:

```scala
graphite {
host = "localhost"
host = ${?INFLUXDB_PORT_ 2003_TCP_ADDR}
port = 2003
port = ${?INFLUXDB_PORT_ 2003_TCP_PORT}
protocol = "tcp"
protocol = ${?INFLUXDB_PORT_ 2003_TCP_PROTO}
}
```

would result in exception like this

```scala
[error] com.typesafe.config.ConfigException$NotResolved: gatling.data.graphite.host has not been resolved, you need to call Config#resolve(), see API docs for Config#resolve()
[error] 	at com.typesafe.config.impl.ConfigImpl.improveNotResolved(ConfigImpl.java:436)
[error] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:154)
[error] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
[error] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
[error] 	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
[error] 	at io.gatling.core.config.GatlingConfiguration$.mapToGatlingConfig(GatlingConfiguration.scala:211)
[error] 	at io.gatling.core.config.GatlingConfiguration$.setUp(GatlingConfiguration.scala:95)
[error] 	at io.gatling.app.Gatling.start(Gatling.scala:68)
[error] 	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:59)
[error] 	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:49)
[error] 	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:48)
[error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error] 	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

I haven't looked into the gatling code before and was only writing simulations scenarios, and thus my knowledge is quite limited, however from what I've seen it might be possible to fix it by calling `resolve()` here:
https://github.com/gatling/gatling/blob/84f8d6e7b44f298c8e5e1f279cd24e88e32811fe/gatling-core/src/main/scala/io/gatling/core/config/GatlingConfiguration.scala#L74

References:
* https://github.com/typesafehub/config#optional-system-or-env-variable-overrides
* http://typesafehub.github.io/config/latest/api/com/typesafe/config/ConfigException.NotResolved.html

**Comment by slandelle** [comment] 2015-03-17 15:55
Duplicate of #2621

**Closed by slandelle** 2015-03-17 15:55 UTC

**Comment by slandelle** [comment] 2015-03-17 15:57
@denvazh Your colleague @knshiro fixed it one hour ago ;)

**Comment by denvazh** [comment] 2015-03-18 04:48
@slandelle Sorry for the duplicate! I started filling in the issue before it appeared and was quite surprised when it was already merged :smile:

**Comment by slandelle** [comment] 2015-03-18 09:19
We love contribs, so we try to check them as quick as we can.
