### ISSUE TITLE
Gatling 3 - RequestTimeoutException

### ISSUE THREAD

**Issue by mkt1988** [gatling/gatling#3750] opened 2019-06-17 07:38 UTC
I'm currently using Gatling 3.1.2 which is the latest version and I have ran many performance tests using gatling and there were no major issues for my testing until this week.

Error

> 00:15:59.509 [WARN ] i.g.h.e.GatlingHttpListener - Request 'Homepage' failed for user 3 io.gatling.http.client.impl.RequestTimeoutException: Request timeout to after 60000 ms

I have 4 to 5 different hosts that my performance tests uses and one of the URI is creating this problem. 
The health check URL for that host is responding 200 but one thing I observed is the URI which is timing out has **very huge response content security policy header** (I'm thinking it might be due to this)

I have tried both with proxy and without proxy. Have also used ahc httpClientCodecMaxHeaderSize in gatling.conf but this is decpricated.

Please help

**Comment by mkt1988** [comment] 2019-06-17 07:42
this is my internal site and is there a way I can increase the response header size?

**Comment by slandelle** [comment] 2019-06-17 07:51
Do a tcp dump, eg with Wireshark, and check if your server sends a proper payload.
Also check content length header matches actual payload size.

If you can’t provide a public reproducer, I’m afraid there’s nothing we can do.

**Comment by mkt1988** [comment] 2019-06-17 09:33
I think mine is same issue as this - https://groups.google.com/forum/#!topic/gatling/D6imHXK5RnQ

**Comment by slandelle** [comment] 2019-06-17 09:47
Can't say. Again, nothing we can investigate without being able to reproduce on our side.

**Comment by slandelle** [comment] 2019-06-19 10:46
> Have also used ahc httpClientCodecMaxHeaderSize in gatling.conf but this is decpricated.

Yes, because header size is no longer limited.

Could you please provide a way to reproduce on our side. Otherwise I'll have to close.

**Comment by slandelle** [comment] 2019-06-27 08:53
Closing for now. Feel free to ping if you can provide more information.

**Closed by slandelle** 2019-06-27 08:53 UTC
