### ISSUE TITLE
Throttle brakes scenario logic. 

### ISSUE THREAD

**Issue by kasheylm** [gatling/gatling#2785] opened 2015-08-05 13:36 UTC
It works fine if your scenario contains of one request\action.
But if you had implemented some business logic in scenario which contains from several http requests than throttling skips requests randomly.
As a result my business flow is broken.

For example, I have 25 requests in my scenario.
And I want to to run it in 100 threads during 1 hour. Without throttling "active users" goes up to thousands. If I use throttling

```scala
setUp(scn.inject(atOnceUsers(100)).throttle(
    jumpToRps(100),   
    holdFor(1 hour)
  ).protocols(httpProtocol))
```

then I see in report statistics not for all 25 requests - some of them randomly dropped.
It may be 10-15 request but should be 25.

I have tried various configuration for throttling but it always fails.
Could you advice something?

**Comment by slandelle** [comment] 2015-08-05 14:50
Could you provide a reproducer, please?

**Comment by kasheylm** [comment] 2015-08-05 15:12
I may send you my script but you cannot run it because of security.
I set time for 1 minute to do it faster for you.

So please have a look at details tab in report - list of requests is not
full.
Should me much more.


2015-08-05 17:50 GMT+03:00 Stephane Landelle <notifications@github.com>:

> Could you provide a reproducer, please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gatling/gatling/issues/2785#issuecomment-128022998>.
>

package com.rokittech.golokal

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._
import scala.language.postfixOps
import scala.util.Random

class BusinessFlowDuringTime extends BaseTest {

  val scn = scenario("Business flow test.")

    .exec(session => session.set("UUID", Random.nextLong().abs))

    .exec(http("create user")
    .post("/businesses/signup")
    .body(ElFileBody("bodies/CreateBusinessUser.ssp"))
    .check(status.is(201))
    .check(header("X-Auth-Token").saveAs("token")))
    .pause(1)

    .repeat(10) {
       exec(session => session.set("UUID", Random.nextLong().abs))

      .exec(http("create gallery image")
      .post("/businesses/me/gallery")
      .header("X-Auth-Token", "${token}")
      .body(ElFileBody("bodies/CreateGalleryImageBig.ssp"))
      .check((jsonPath("$.id")).saveAs("galleryImageId"))
      .check(status.is(201)))
      .pause(1)

       .exec(http("create business image")
         .post("/businesses/me/images")
         .header("X-Auth-Token", "${token}")
         .body(ElFileBody("bodies/CreateBusinessImage.ssp"))
         .check(status.is(201)))
    }

    .exec(http("update business cover")
    .put("/businesses/me/images/cover")
    .header("X-Auth-Token", "${token}")
    .body(ElFileBody("bodies/UpdateBusinessCover.ssp"))
    .check(status.is(200)))
    .pause(1)

    .exec(http("get business images")
    .get("/businesses/me/images")
    .header("X-Auth-Token", "${token}")
    .check(status.is(200)))
    .pause(1)

    .exec(http("get active subscription")
    .get("/billings/me/subscription")
    .header("X-Auth-Token", "${token}")
    .check(status.is(200))
    .check((jsonPath("$.postsLimit").ofType[Int]).saveAs("postsLimit")))
    .pause(1)

    .repeat("${postsLimit}") {
       feed(location)
       .exec(session => session.set("startTime", System.currentTimeMillis()))
       .exec(session => session.set("endTime", System.currentTimeMillis() + 14400000))

      .exec(http("create promotion")
      .post("/businesses/me/promotions")
      .header("X-Auth-Token", "${token}")
      .body(ElFileBody("bodies/CreatePromotion.ssp"))
      .check(status.is(201)))
    }
)
  setUp(scn.inject(atOnceUsers(200)).throttle(
//    reachRps(80) in (10 seconds),
//    holdFor(30 seconds),
    jumpToRps(200),
    holdFor(15 minutes)
  ).protocols(httpProtocol))
}

**Comment by kasheylm** [comment] 2015-08-05 15:17
I will be available in skype kashey.veselovskiy in hour.
Dont hesitate to contact me.

2015-08-05 18:12 GMT+03:00 Kashey <kasheylm@gmail.com>:

**Comment by slandelle** [comment] 2015-08-05 15:18
Sorry, but the point is indeed to be able to run it and reproduce. If you can't build a reproducer against your own platform  you can maybe build one against a public website without any harmful load.

**Comment by slandelle** [comment] 2015-08-05 15:19
Sorry, on vacation atm :)
Plus Skype calls are for customers who purchased support :)

**Comment by kasheylm** [comment] 2015-08-05 15:21
Ok, I will try to do it.

One more questions

How should I generate constant users per sec and requests per sec in my
case (for script I've send you)?
I tried  constantUsersPerSec(1000) during(15 minutes) and after that I saw
20k active users in report.

2015-08-05 18:18 GMT+03:00 Stephane Landelle <notifications@github.com>:

**Comment by slandelle** [comment] 2015-08-08 08:16
UsersPerSec is an arrival rate at your scenario entry. If your system/scenario can't evacuate them, they will pile up until you'll crash.

**Comment by slandelle** [comment] 2015-08-24 12:07
Sorry, can't reproduce. Which version do you use?

**Comment by kasheylm** [comment] 2015-08-31 08:11
Gatling  - 2.1.7.
OS - Windows 8 x64

2015-08-24 15:07 GMT+03:00 Stephane Landelle <notifications@github.com>:

**Comment by slandelle** [comment] 2015-08-31 09:07
Sorry, I really can't reproduce. I'm closing for now. If you can but a test case so I can reproduce, please ping and I'll reopen.

**Closed by slandelle** 2015-08-31 09:07 UTC
