### ISSUE TITLE
[Bug] user not recovering from java.nio.charset.CharacterCodingException

### ISSUE THREAD

**Issue by mxbossard** [gatling/gatling#3040] opened 2016-06-07 08:40 UTC
Hi there,

I am still using v2.2.0.

My simulation setup get some garbage from the tested servers when they are swamped. This lead the simulation to leave users in a stuck situation. After a certain amount of time all the users are stuck and don't send requests anymore. My simulation was started 14 hours ago, no more request are sent, but JVM still running, and graphite still receiving activity from 797 active users.

For my last simulation I use 801 users and I got 806 CharacterCodingException in logs. I think it might be this exception wich stuck the simulation users.

Exception exemple : 
`18:58:23.387 [DEBUG] i.g.h.a.AsyncHandler - Request 'request_11' failed for user 442
java.nio.charset.CharacterCodingException: null
        at io.gatling.http.util.Utf8ByteBuffersDecoder.write(ByteBuffersDecoder.scala:135)
        at io.gatling.http.util.Utf8ByteBuffersDecoder.io$gatling$http$util$Utf8ByteBuffersDecoder$$$anonfun$6(ByteBuffersDecoder.scala:144)
        at io.gatling.http.util.Utf8ByteBuffersDecoder.io$gatling$http$util$Utf8ByteBuffersDecoder$$$anonfun$6$adapted(ByteBuffersDecoder.scala:142)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at io.gatling.http.util.Utf8ByteBuffersDecoder.decode(ByteBuffersDecoder.scala:142)
        at io.gatling.http.util.ByteBuffersDecoder$.decode(ByteBuffersDecoder.scala:52)
        at io.gatling.http.util.BytesHelper$.byteBufsToString(BytesHelper.scala:58)
        at io.gatling.http.response.StringResponseBody$.apply(ResponseBody.scala:62)
        at io.gatling.http.response.ResponseBuilder.build(ResponseBuilder.scala:189)
        at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:127)
        at io.gatling.http.ahc.AsyncHandler.onCompleted(AsyncHandler.scala:46)
        at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:188)
        at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:223)
        at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:58)
        at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:159)
        at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:189)
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
`

Bye !

**Comment by slandelle** [comment] 2016-06-07 08:55
AFAIK, this is a duplicate of #2981 that has been fixed in 2.2.1.

Closing for now. Please report if you still run into this issue after upgrading.

**Closed by slandelle** 2016-06-07 08:55 UTC
