### ISSUE TITLE
Feeder strategy queue() don't wait for all requests and not flush all data to simulation.log after "Feeder XXX is now empty, stopping engine"

### ISSUE THREAD

**Issue by gemiusz** [gatling/gatling#4463] opened 2023-09-14 12:37 UTC
Gatling: 3.9.5 (gatling-charts-highcharts-bundle-3.9.5)
OS: Windows 10 Pro
JDK: jdk-17.0.4

Feeder strategy queue() don't wait for all requests and not flush all data to simulation.log after "Feeder XXX is now empty, stopping engine".

**Comment by slandelle** [comment] 2023-09-14 13:15
That’s intended. An empty feeder is a test design error, we don’t want to bother doing a graceful shutdown in this case, too complicated.

**Comment by Amerousful** [comment] 2023-09-15 11:13
`maxUsers?` :)

**Comment by gemiusz** [comment] 2023-09-15 14:15
So if this is intentional I wondering how to do a Simulation where when data in feeder has run out simulation is end gracefully. 
I thinking about solution for case mentioned here -> https://github.com/gatling/gatling/issues/4462#issuecomment-1713889195
Other case is that I have "one shot" test data and I want to use all of them in Simulation but I'm not sure how long Silulation can take.

**Comment by slandelle** [comment] 2023-09-20 16:48
The best way is to have a sufficient amount of data in the feeder. You can protect against a crash and bypass the faulty requests: wrap the request with a test comparing a counter compared against the [feeder records count](https://gatling.io/docs/gatling/reference/current/core/session/feeder/#recordsCount. But you can't interrupt the injection profile.

**Comment by slandelle** [comment] 2023-09-20 16:53
Closing this ticket here as it's the expected behavior.

When a feeder becomes empty, we have no way to determine the correct behavior.
A graceful shutdown is impossible to define (stop injecting new users and let the other users terminates? but what if some other users still run for hours, doesn't the test still makes sense?).
So we're treating this situation as a fatal user error.

**Closed by slandelle** 2023-09-20 16:53 UTC
