### ISSUE TITLE
How to configure Gatling in Gradle with Kotlin-style?

### ISSUE THREAD

**Issue by pandoras-toolbox** [gatling/gatling#4358] opened 2022-12-09 16:17 UTC
I tried to convert the Gatling Gradle example from Groovy to Kotlin.

I do not know how to convert this part (Groovy-style Gradle):
```
gatling {
    logLevel = 'WARN'
    logHttp = 'NONE'
}
```

I tried (Kotlin-style Gradle):
```
gatling {
    logLevel = "WARN"
    logHttp = "NONE"
}
```

But it does not accept it because of:
> Cannot access 'io.gatling.gradle.JvmConfigurable.Trait.FieldHelper' which is a supertype of 'io.gatling.gradle.GatlingPluginExtension'. Check your module classpath for missing or conflicting dependencies

That is like Chinese to me (a language which I do not speak I should add).

See [my fork](https://github.com/pandoras-toolbox/gatling-gradle-plugin-demo-java-for-issue-4091/blob/main/subprojects/load/load.gradle.kts) of a Gatling example.

How to do this with Kotlin in Gradle?

**Comment by slandelle** [comment] 2022-12-09 16:18
Please use our [Community forum](https://community.gatling.io/) for questions, this is a bug tracker.

**Comment by slandelle** [comment] 2022-12-09 16:19
Duplicate of #4337

**Closed by slandelle** 2022-12-09 16:18 UTC

**Comment by pandoras-toolbox** [comment] 2022-12-13 08:23
I did: https://community.gatling.io/t/how-to-configure-gatling-in-gradle-with-kotlin-style/7421/2
