### ISSUE TITLE
Using Gatling 3.0.0-RC2 to run https url would get timeout

### ISSUE THREAD

**Issue by johnsonexosite** [gatling/gatling#3547] opened 2018-10-01 08:15 UTC
[desc]
Run Gatling 3.0.0-RC2 with https url, e.g., Google, would get timeout

[renvironment]
* OS: on macos Mojave
* Maven and JDK info with `mvn -version`
```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_152, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre
Default locale: en_TW, platform encoding: UTF-8
OS name: "mac os x", version: "10.14", arch: "x86_64", family: "mac"
```
[reproduce]
* clone gatling-maven-plugin-demo repo: https://github.com/gatling/gatling-maven-plugin-demo
* Add a test script under package "computerdatabase " as follows

```
package computerdatabase

import io.gatling.core.Predef._
import io.gatling.core.structure.ScenarioBuilder
import io.gatling.http.Predef._
import io.gatling.http.protocol.HttpProtocolBuilder

class TestGoogle extends Simulation {

  val httpProtocol: HttpProtocolBuilder = http.baseUrl("https://www.google.com")

  val scn: ScenarioBuilder = scenario("Gatling3 test google")
    .exec(http("index page")
      .get("/")
      .check(status.is(200)))
    .exec(http("query 'Gatling the load test tool'")
      .get("/search?q=Gatling+the+load+test+tool&oq=Gatling+the+load+test+tool")
      .check(status.is(200))
    )

  setUp(
    scn.inject(
      atOnceUsers(1)
    )
  ).protocols(httpProtocol)
    .assertions(
      global.responseTime.mean.lte(3000)
    )
}
```

* run:
`mvn clean gatling:test -DsimulationClass=computerdatabase.TestGoogle`

[issue happened]
* the request to index page of Google would get timeout
* seeing below errors in logs (using FileAppender and print out DEBUG level and I changed the timeout to 10 seconds in gatling.conf)

```
...
16:03:49.402 [ERROR] i.g.h.c.i.DefaultHttpClient - Failed to install SslHandler
...
16:03:59.397 [WARN ] i.g.h.e.GatlingHttpListener - Request 'index page' failed for user 1
io.gatling.http.client.impl.RequestTimeout$RequestTimeoutException: Request timeout to www.google.com/108.177.125.99:443 after 10000 ms
16:03:59.404 [ERROR] i.g.h.e.r.DefaultStatsProcessor - Request 'index page' failed for user 1: i.g.h.c.i.RequestTimeout$RequestTimeoutException: Request timeout to www.google.com/108.177.125.99:443 after 10000 ms
...
```

* also some debug logs of netty tcnative library loading, not sure if it's related but seems important

```
16:03:47.866 [DEBUG] i.n.u.i.NativeLibraryLoader - Unable to load the library 'netty_tcnative_osx_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:440)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:202)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:191)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:34)
	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:188)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:776)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:452)
	at io.gatling.http.client.impl.DefaultHttpClient.<init>(DefaultHttpClient.java:239)
	at io.gatling.http.engine.DefaultHttpClientFactory.newClient(HttpClientFactory.scala:101)
	at io.gatling.http.engine.HttpEngine$.apply(HttpEngine.scala:44)
	at io.gatling.http.protocol.HttpProtocol$$anon$1.newComponents(HttpProtocol.scala:54)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$1(Protocol.scala:68)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.componentsFactory$1(Protocol.scala:68)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:70)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:72)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:72)
	at io.gatling.http.action.HttpActionBuilder.lookUpHttpComponents(HttpActionBuilder.scala:26)
	at io.gatling.http.action.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.$anonfun$build$1(StructureBuilder.scala:35)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at io.gatling.core.structure.StructureBuilder.build(StructureBuilder.scala:34)
	at io.gatling.core.structure.StructureBuilder.build$(StructureBuilder.scala:33)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:100)
	at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:194)
	at scala.collection.immutable.List.map(List.scala:283)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:194)
	at io.gatling.app.Runner.run0(Runner.scala:92)
	at io.gatling.app.Runner.run(Runner.scala:61)
	at io.gatling.app.Gatling$.start(Gatling.scala:74)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
	at io.gatling.app.Gatling$.main(Gatling.scala:39)
	at io.gatling.app.Gatling.main(Gatling.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
	at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
16:03:47.868 [DEBUG] i.n.u.i.NativeLibraryLoader - netty_tcnative_osx_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /var/folders/w1/6gj1n8l57fgfvrs6gr7k07xr0000gn/T
java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:440)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:202)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:191)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:34)
	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:188)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:776)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:452)
	at io.gatling.http.client.impl.DefaultHttpClient.<init>(DefaultHttpClient.java:239)
	at io.gatling.http.engine.DefaultHttpClientFactory.newClient(HttpClientFactory.scala:101)
	at io.gatling.http.engine.HttpEngine$.apply(HttpEngine.scala:44)
	at io.gatling.http.protocol.HttpProtocol$$anon$1.newComponents(HttpProtocol.scala:54)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$1(Protocol.scala:68)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.componentsFactory$1(Protocol.scala:68)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:70)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:72)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:72)
	at io.gatling.http.action.HttpActionBuilder.lookUpHttpComponents(HttpActionBuilder.scala:26)
	at io.gatling.http.action.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.$anonfun$build$1(StructureBuilder.scala:35)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at io.gatling.core.structure.StructureBuilder.build(StructureBuilder.scala:34)
	at io.gatling.core.structure.StructureBuilder.build$(StructureBuilder.scala:33)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:100)
	at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:194)
	at scala.collection.immutable.List.map(List.scala:283)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:194)
	at io.gatling.app.Runner.run0(Runner.scala:92)
	at io.gatling.app.Runner.run(Runner.scala:61)
	at io.gatling.app.Gatling$.start(Gatling.scala:74)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
	at io.gatling.app.Gatling$.main(Gatling.scala:39)
	at io.gatling.app.Gatling.main(Gatling.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
	at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
	Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
		at java.lang.Runtime.loadLibrary0(Runtime.java:870)
		at java.lang.System.loadLibrary(System.java:1122)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336)
		at java.security.AccessController.doPrivileged(Native Method)
		at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328)
		at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306)
		... 46 common frames omitted
16:03:47.891 [DEBUG] i.n.u.i.NativeLibraryLoader - Successfully loaded the library /var/folders/w1/6gj1n8l57fgfvrs6gr7k07xr0000gn/T/libnetty_tcnative_osx_x86_647463786736670737598.dylib
16:03:47.892 [DEBUG] i.n.h.s.OpenSsl - Initialize netty-tcnative using engine: 'default'
16:03:47.892 [DEBUG] i.n.h.s.OpenSsl - netty-tcnative using native library: BoringSSL
```

[other information]
* I also tested the TestGoogle script directly with 3.0.0-RC2 Gatling runnable(gatling.sh), also got timeout.
* Also test with other https url, e.g., CNN, and got timeout, too.

**Comment by slandelle** [comment] 2018-10-01 09:40
Thanks for reporting. Actually, this is a duplicate of #3537 that will be fixed in RC3 to be released tomorrow.

**Closed by slandelle** 2018-10-01 09:40 UTC

**Comment by johnsonexosite** [comment] 2018-10-01 10:00
Nice, thanks for the response.

**Comment by damianbl** [comment] 2018-10-09 07:47
I'm on version 3.0.0-RC3 and I still experience this issue.

**Comment by slandelle** [comment] 2018-10-09 07:59
@damianbl Could you please provide a reproducer we can run on our side?

**Comment by damianbl** [comment] 2018-10-09 08:04
Actually this is my test for the company portal but I will try to prepare sth quickly.

**Comment by slandelle** [comment] 2018-10-09 08:13
@damianbl Making things clear: if you have an issue, it's a different one from the one here. The reproducer @johnsonexosite provided definitively works with 3.0.0-RC3. If you can come up with a reproducer for your issue, please open a dedicated issue.
