### ISSUE TITLE
Gatling SBT Plugin issue with sbt run task

### ISSUE THREAD

**Issue by TimGraf** [gatling/gatling#2837] opened 2015-10-19 19:29 UTC
The plugin works fine when running `sbt test`.  My issue is that when I run `sbt run` I recieve the following error.  I wouldn't expect gatling tests to run with the `sbt run` task.

```
sbt run
[info] Loading global plugins from /Users ...
[info] Loading project definition from /Users ...
[info] Set current project to sherlock (in build file:/Users ...)
[warn] No main class detected
java.lang.RuntimeException: No main class detected.
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last gatling:run for the full output.
[error] (gatling:run) No main class detected.
```

**Comment by slandelle** [comment] 2015-10-20 11:56
@pdalpra could confirm, but I think it's a duplicate of #2763. In the next release, Gatling tasks will only trigger when prefixed with `gatling:`.

**Closed by slandelle** 2015-10-20 11:56 UTC

**Comment by pdalpra** [comment] 2015-10-20 12:20
`sbt run` is not the way to run Gatling simulations.
You run them like unit tests, using `gatling:test`, `gatling:testOnly`, etc...
The run task has only one goal : run a main class in your project.

**Comment by slandelle** [comment] 2015-10-20 12:22
@pdalpra Yeah, but the logs made me believe that `gatling:run` was triggered when only launching `sbt:run`:

`[trace] Stack trace suppressed: run last gatling:run for the full output.`

**Comment by pdalpra** [comment] 2015-10-20 12:24
@slandelle Yep, that's one of the consequences of #2763.

**Comment by Sarazh** [comment] 2016-02-18 14:43
I have the same problem with @TimGraf  while running `sbt run`.  I didn't find solution for that. How can I launch `sbt run` without triggering `gatling:run` ?
