### ISSUE TITLE
Recorder: javax.net.ssl.SSLException: Received fatal alert: handshake_failure when trying to record site requiring client auth

### ISSUE THREAD

**Issue by tboloo** [gatling/gatling#2864] opened 2015-11-25 22:03 UTC
Here is my scenario:
I have a web application that I would like to test, which is secured by a self-signed certificate pair, that is a client needs to show it's pair of a certificate to successfully connect to website. 
Now I have configured Gatling to use custom keystore (one that I supplied with the mentioned key), however when I try to navigate to the service I get the timeout in the browser, and SSLException in Gatling.
I have tried several apporached, like creating new keystore, converting keys from p12 to jks, with no luck unfortunately.
Any help appreciated...

**Comment by slandelle** [comment] 2015-11-26 12:44
I'm afraid you'll have to provide a reproducer = sample app with such security.

**Comment by slandelle** [comment] 2016-02-27 21:58
Duplicate of #2909. How-to implement instructions provided there. Should be pretty easily to contribute.

**Closed by slandelle** 2016-02-27 21:58 UTC
