### ISSUE TITLE
[BUG] Gatling 3.x miscalculate the response time in the first few seconds

### ISSUE THREAD

**Issue by keithmork** [gatling/gatling#3736] opened 2019-05-22 14:05 UTC
I ran the same script in both 2.3.1 and 3.1.2, the average ping to the site is under 30ms.

The result of 2.3.1 is correct, but 3.1.2 always shows that there's "no response" in the first 3-10 seconds.

---

2.3.1: 

```sh
================================================================================
---- Global Information --------------------------------------------------------
> request count                                        600 (OK=600    KO=0     )
> min response time                                     17 (OK=17     KO=-     )
> max response time                                    211 (OK=211    KO=-     )
> mean response time                                    25 (OK=25     KO=-     )
> std deviation                                         14 (OK=14     KO=-     )
> response time 50th percentile                         22 (OK=22     KO=-     )
> response time 75th percentile                         24 (OK=24     KO=-     )
> response time 95th percentile                         35 (OK=35     KO=-     )
> response time 99th percentile                         95 (OK=95     KO=-     )
> mean requests/sec                                     20 (OK=20     KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                           600 (100%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            0 (  0%)
> failed                                                 0 (  0%)
================================================================================
```

![](https://raw.githubusercontent.com/keithmork/keithmork.github.io/master/img/screenshot/bug-report/20190522-gatling-2.3.1.png)

---

3.1.2:

```sh
================================================================================
---- Global Information --------------------------------------------------------
> request count                                        595 (OK=595    KO=0     )
> min response time                                     17 (OK=17     KO=-     )
> max response time                                   8154 (OK=8154   KO=-     )
> mean response time                                  1315 (OK=1315   KO=-     )
> std deviation                                       2367 (OK=2367   KO=-     )
> response time 50th percentile                         23 (OK=23     KO=-     )
> response time 75th percentile                       1469 (OK=1469   KO=-     )
> response time 95th percentile                       7004 (OK=7004   KO=-     )
> response time 99th percentile                       7887 (OK=7887   KO=-     )
> mean requests/sec                                 19.833 (OK=19.833 KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                           430 ( 72%)
> 800 ms < t < 1200 ms                                  11 (  2%)
> t > 1200 ms                                          154 ( 26%)
> failed                                                 0 (  0%)
================================================================================
```

![](https://raw.githubusercontent.com/keithmork/keithmork.github.io/master/img/screenshot/bug-report/20190522-gatling-3.1.2.png)

---

script:

```scala
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class Test extends Simulation {
    val httpConf = http
        .baseURL("http://www.baidu.com")  // .baseUrl in 3.x

    val scn = scenario("Demo")
        .exec(
            http("test")
                .get("/")
        )

    setUp(
        scn.inject(
            constantUsersPerSec(20).during(30.seconds).randomized,
        ).protocols(httpConf)
    )
}
```

- OS: macOS 10.14.4
- JDK: 1.8.0_u181

**Comment by keithmork** [comment] 2019-05-22 14:17
I also ran the same script in 3.1.2 maven version, with step-by-step debug. The test actually starts from 139s, and this time the result is right.

```sh
================================================================================
2019-05-22 21:57:48                                         139s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=0     )


---- Demo ----------------------------------------------------------------------
[                                                                          ]  0%
          waiting: 621    / active: 0      / done: 0     
================================================================================


================================================================================
2019-05-22 21:57:49                                         140s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=6      KO=0     )
> test                                                     (OK=6      KO=0     )

---- Demo ----------------------------------------------------------------------
[                                                                          ]  0%
          waiting: 615    / active: 0      / done: 6     
================================================================================


================================================================================
2019-05-22 21:57:54                                         145s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=115    KO=0     )
> test                                                     (OK=115    KO=0     )

---- Demo ----------------------------------------------------------------------
[#############                                                             ] 18%
          waiting: 506    / active: 0      / done: 115   
================================================================================

...

================================================================================
2019-05-22 21:58:18                                         169s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=621    KO=0     )
> test                                                     (OK=621    KO=0     )

---- Demo ----------------------------------------------------------------------
[##########################################################################]100%
          waiting: 0      / active: 0      / done: 621   
================================================================================

Simulation com.al.Test completed in 65 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...

================================================================================
---- Global Information --------------------------------------------------------
> request count                                        621 (OK=621    KO=0     )
> min response time                                     16 (OK=16     KO=-     )
> max response time                                    374 (OK=374    KO=-     )
> mean response time                                    26 (OK=26     KO=-     )
> std deviation                                         26 (OK=26     KO=-     )
> response time 50th percentile                         21 (OK=21     KO=-     )
> response time 75th percentile                         24 (OK=24     KO=-     )
> response time 95th percentile                         37 (OK=37     KO=-     )
> response time 99th percentile                         90 (OK=90     KO=-     )
> mean requests/sec                                 20.032 (OK=20.032 KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                           621 (100%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            0 (  0%)
> failed                                                 0 (  0%)
================================================================================
```

I guess Gatling 3.x has too many heavy work to do when it starts and those "response times" are something like this?

```sh
timer starts
do lots of things ...
request sent
response arrived
timer ends
```

**Comment by keithmork** [comment] 2019-05-22 17:25
That's wired...

Another example, the max response time in gatling's log is 4x greater than what I see in wireshark.

The 1st request is sent on 00:41:22.949, wired results appear from here on to 00:41:27, within 4-5s right after test started.

```sh
ping www.baidu.com
PING www.a.shifen.com (182.61.200.6): 56 data bytes

httping http://www.baidu.com
PING www.baidu.com:80 (/):
connected to 182.61.200.7:80 (312 bytes), seq=0 time= 94.24 ms

# wireshark filter:
ip.addr in {182.61.200.6 182.61.200.7} && http.time > 0.9
# only 1 result:
[Time since request: 0.917414000 seconds]
```

```sh
================================================================================
2019-05-23 00:41:25                                           5s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=0     )


---- Demo ----------------------------------------------------------------------
[--------                                                                  ]  0%
          waiting: 546    / active: 62     / done: 0     
================================================================================


================================================================================
2019-05-23 00:41:30                                          10s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=158    KO=0     )
> test                                                     (OK=158    KO=0     )

---- Demo ----------------------------------------------------------------------
[###################-                                                      ] 25%
          waiting: 449    / active: 1      / done: 158   
================================================================================

......

Simulation com.al.Test completed in 30 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...

================================================================================
---- Global Information --------------------------------------------------------
> request count                                        608 (OK=608    KO=0     )
> min response time                                     91 (OK=91     KO=-     )
> max response time                                   3736 (OK=3736   KO=-     )
> mean response time                                   337 (OK=337    KO=-     )
> std deviation                                        703 (OK=703    KO=-     )
> response time 50th percentile                         95 (OK=95     KO=-     )
> response time 75th percentile                         98 (OK=98     KO=-     )
> response time 95th percentile                       2293 (OK=2293   KO=-     )
> response time 99th percentile                       3279 (OK=3279   KO=-     )
> mean requests/sec                                 19.613 (OK=19.613 KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                           540 ( 89%)
> 800 ms < t < 1200 ms                                  14 (  2%)
> t > 1200 ms                                           54 (  9%)
> failed                                                 0 (  0%)
================================================================================

Reports generated in 0s.
```

simulation.log:

```sh
#1  RUN	com.al.Test	test	1558543280461	 	3.1.2
#2  USER    Demo    1   START   1558543282906   1558543282906
#129  REQUEST 1       test    1558543282949   1558543286353   OK
#130  USER   Demo    1   END 1558543282906   1558543286354
```

```py
>>> datetime.fromtimestamp(1558543280461 / 1000).strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
'2019-05-23 00:41:20.461'
>>> datetime.fromtimestamp(1558543282906 / 1000).strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
'2019-05-23 00:41:22.906'
>>> datetime.fromtimestamp(1558543282949 / 1000).strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
'2019-05-23 00:41:22.949'
>>> datetime.fromtimestamp(1558543286353 / 1000).strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
'2019-05-23 00:41:26.353'
>>> datetime.fromtimestamp(1558543286354 / 1000).strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
'2019-05-23 00:41:26.354'
>>> 1558543286354 - 1558543282906
3448
>>> 1558543286354 - 1558543282949
3405
```

**Comment by slandelle** [comment] 2019-05-22 19:44
Try using a java profiler to figure out where your threads spend time (possibly blocked or waiting).
I really can't reproduce on my side and you're the first one to report experiencing this problem.

**Comment by slandelle** [comment] 2019-05-28 13:52
Closing. Feel free to ping if you find your problem.

**Closed by slandelle** 2019-05-28 13:52 UTC

**Comment by keithmork** [comment] 2019-05-30 04:36
@slandelle I solved this issue.  

The thread dump of 3.1.2 shows that the 1st http thread got stuck at `sun.management.VMManagementImpl.getVmId` for abount 2 secs.

```sh
"gatling-http-1-1" #21 prio=5 os_prio=31 tid=0x00007fc4cb2f8800 nid=0x9503 runnable [0x0000700006e75000]
   java.lang.Thread.State: RUNNABLE
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
	- locked <0x000000078a1f1a70> (a java.lang.Object)
	at sun.management.VMManagementImpl.getVmId(VMManagementImpl.java:140)
	at sun.management.RuntimeImpl.getName(RuntimeImpl.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.channel.DefaultChannelId.defaultProcessId(DefaultChannelId.java:120)
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:77)
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:112)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:84)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioByteChannel.<init>(AbstractNioByteChannel.java:66)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:104)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:94)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:87)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:80)
	at io.gatling.http.client.impl.DefaultHttpClient$EventLoopResources$$Lambda$387/1903927611.newChannel(Unknown Source)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:156)
	at io.gatling.http.client.impl.DefaultHttpClient.openNewChannelRec(DefaultHttpClient.java:602)
	at io.gatling.http.client.impl.DefaultHttpClient.openNewChannel(DefaultHttpClient.java:576)
	at io.gatling.http.client.impl.DefaultHttpClient.sendTxWithNewChannel(DefaultHttpClient.java:480)
	at io.gatling.http.client.impl.DefaultHttpClient.lambda$sendTx$2(DefaultHttpClient.java:365)
	at io.gatling.http.client.impl.DefaultHttpClient$$Lambda$397/837419853.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:152)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:33)
	at io.gatling.http.client.impl.DefaultHttpClient.sendTx(DefaultHttpClient.java:347)
	at io.gatling.http.client.impl.DefaultHttpClient.lambda$sendRequest$0(DefaultHttpClient.java:252)
	at io.gatling.http.client.impl.DefaultHttpClient$$Lambda$385/1627883152.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None
```

The solution is easy: just add local hostname to /etc/hosts

```sh
127.0.0.1	localhost your-local-hostname
```

> https://github.com/netty/netty/issues/6454  
https://stackoverflow.com/questions/39636792/jvm-takes-a-long-time-to-resolve-ip-address-for-localhost/39698914#39698914  

---

For anyone who has similar problem, here's the script:

```sh
#!/bin/bash

simulation_class="$1"

# ---

if [ -f "$GATLING_HOME/bin/gatling.sh" ]; then
    $GATLING_HOME/bin/gatling.sh -s $simulation_class > stdout.log 2>&1 &
else
    mvn gatling:test -Dgatling.simulationClass=$simulation_class > stdout.log 2>&1 &
fi

for i in {1..60}; do
    sleep 1

    process=$(ps aux | grep -v grep | grep -v IDEA | grep java | grep gatling)
    echo $process
    pid=$(echo $process | awk '{print $2}')
    echo PID: $pid

    if [ -n "$pid" ]; then
        [ $i -ge 10 ] && count=$i || count=0$i
        jstack -l "$pid" > stack$count.log
    else
        [ $i -ge 10 ] && break
    fi
done
```

**Comment by keithmork** [comment] 2019-05-30 04:53
Though I still a bit conserned about the way gatling calculates response times.

If my API expects P99.9 RT <= 20ms and gatling threads need longer than that to init, the test may be incorrectly marked as "failed".

**Comment by slandelle** [comment] 2019-05-31 07:45
```
at io.netty.channel.DefaultChannelId.defaultProcessId(DefaultChannelId.java:120)
```

https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/DefaultChannelId.java#L120

This class hasn't changed since 2017, see [here](https://github.com/netty/netty/commits/4.1/transport/src/main/java/io/netty/channel/DefaultChannelId.java). Meaning that your original statement `The result of 2.3.1 is correct, but 3.1.2 always shows that there's "no response" in the first 3-10 seconds.` is most likely wrong as both Gatling 2.3 and 3.1 use Netty 4.1. Were you actually running Gatling 2.3 and 3.1 from different boxes where the 2.3 one was properly configured and not the 3.1 one?

> gatling threads need longer than that to init, the test may be incorrectly marked as "failed".

Netty is using JMX on initialization to fetch process id (see code line link above). Just fix your box configuration and you'll be fine.

**Comment by keithmork** [comment] 2019-06-01 05:23
> Were you actually running Gatling 2.3 and 3.1 from different boxes where the 2.3 one was properly configured and not the 3.1 one?
@slandelle Nope, they were running from the same box and all the configs were unchanged when I did the tests above.

**Comment by slandelle** [comment] 2019-06-03 07:03
I’ve made some changes wrt initialization order that might help, see #3745.
However, the core issue was that your box wasn’t properly configured (localhost missing /etc/hosts).

**Comment by lovromazgon** [comment] 2020-06-22 12:04
FWIW, I'm still experiencing the same issue. My `/etc/hosts` file already contains the mapping for localhost.

Gatling: 3.3.1
OS: macOS 10.15.5
JDK: OpenJDK 13.0.2

I'm also attaching the log output ([logs.zip](https://github.com/gatling/gatling/files/4813044/logs.zip)) generated by the script shared in [this comment](https://github.com/gatling/gatling/issues/3736#issuecomment-497199167).
