### ISSUE TITLE
Jenkins: Performance trend is empty

### ISSUE THREAD

**Issue by lalkhum** [gatling/gatling#2792] opened 2015-08-21 14:30 UTC
I use gatling as my load test tool and I have problem viewing the performance trend.

The error is as follows.

Uncaught TypeError: Cannot read property 'CategoryAxisRenderer' of undefined

I wonder if someone also has come across this issue?

**Comment by gempesaw** [comment] 2015-09-18 19:05
I think I'm seeing the same issue.

Jenkins ver. 1.565.2
Jenkins Gatling Plugin 1.1.1

When clicking on `Gatling` in the left sidebar of the Project page, it shows the `Performance Trend` page but there are no graphs visible on the page, along with a few console errors.

![Performance Trend](https://monosnap.com/file/ybwJ5bqsuROnNbj4kct0bXLkHvi4Ok.png)

**Comment by gsmachado** [comment] 2015-10-05 08:20
Hello guys,

First, thanks for this very nice plugin! :-)

I'm facing the exact same problem with the following versions:
- Jenkins: 1.628, running on Windows
- Gatling plugin: 1.1.1

I'm trying to visualize the performance trend with Firefox 41.0.1 and Chrome 45.0.2454.

The error shown in Firefox is attached.

Let us know about a possible workaround, since this is affecting all the major new versions.

![bug-jenkins-gatling-plugin](https://cloud.githubusercontent.com/assets/2124276/10275782/86da9c4c-6b4a-11e5-8fd1-9848830828ec.png)

**Comment by esramirez** [comment] 2015-10-23 13:53
having similar issue with firefox and chrome. 
The gatlin jenkin plugin version is: 1.1.1 
Gatlin version is:  1.596

**Comment by gsmachado** [comment] 2015-10-23 13:57
@slandelle can you give us any hints on why is this happening? Maybe you can enlighten us, and then, I could hack around a bit to come up with a fix (or, at least, try to). :-)

**Comment by slandelle** [comment] 2015-10-24 11:03
I'd say that, once again, the Jenkins people broke compatibility...
Maybe something like jQuery version.

**Comment by esramirez** [comment] 2015-10-26 14:04
I am working on integrating Gatling to our CI process and would be great to see this bug get addressed. If there is anything i can do to help please let me know.

**Comment by slandelle** [comment] 2015-10-26 14:11
@esramirez We're pretty busy here, sorry. Please consider contributing. Or if you can't and are really in a rush, you can also consider our [support offer](http://gatling.io/#/services).

**Comment by gempesaw** [comment] 2015-10-26 14:26
I've started digging in to this to figure out what's wrong, and so far I actually haven't been able to reproduce on a clean install of jenkins.

```
docker pull jenkins:1.565.2
docker run -p 8080:8080 jenkins

# open up jenkins on 8080, 
# install gatling plugin
# install github plugin
# install maven in jenkins system preferences
# create maven project, add git repo https://github.com/gatling/gatling-maven-plugin-demo
# add post build step for gatling
# "build now"
```

and it worked swimmingly for the most recent version of Jenkins as well as the specific version where I was seeing the error. So, I'm pretty confused as to what else could be causing the issue. I've asked our SiteOps people for a list of installed plugins to see if there's some unexpected conflict there. 

In my case, I've found that the issue is that `jQuery.jqPlot` is entirely undefined, so of course none of the graphs will appear since the jqPlot library isn't available to do its job, but as mentioned, I'm not sure why this is happening, or how to fix it.

**Comment by esramirez** [comment] 2015-10-26 14:33
i am also using  jenkins 1.56.2 but i noticed there is a new version, 1.635. Have you tried it yet?

**Comment by gsmachado** [comment] 2015-10-26 14:45
The issue remains with Jenkins 1.635.

**Comment by gsmachado** [comment] 2015-10-26 14:54
@gempesaw, the funny thing is: the "Mean response time trend" works fine, which also uses the jqPlot object (as far as I've could see).

**Comment by gempesaw** [comment] 2015-10-26 16:07
> I'd say that, once again, the Jenkins people broke compatibility...
> Maybe something like jQuery version.

Oh, I see, slandelle's comment was actually exactly the issue, I just didn't understand it! Installing the `jQuery` plugin along with the `gatling` plugin makes the problem occur immediately. Uninstalling the `jQuery` plugin makes the issue go away. Still not sure how to fix it yet. 

I verified that with 1.596 and 1.635 but it seems pretty evident that the plugin conflict is the issue, not the Jenkins version.

**Comment by gsmachado** [comment] 2015-10-26 16:07
Hello all,

I've found the issue.

It's an incompatibility with the jQuery Jenkins plugin (https://wiki.jenkins-ci.org/display/JENKINS/jQuery+Plugin).

**Comment by gsmachado** [comment] 2015-10-26 16:08
Oh, yes, it seems we posted/found at the same time. :-) Good. :+1:

**Comment by esramirez** [comment] 2015-10-27 13:05
the workaround worked for me! thanks alot

**Comment by slandelle** [comment] 2016-01-18 13:38
Closed by https://github.com/jenkinsci/gatling-plugin/pull/11

**Closed by slandelle** 2016-01-18 13:38 UTC
Labels: Module - Jenkins, Type - Bug
