### ISSUE TITLE
HTTP: Premature close in Gatling 3.3.1

### ISSUE THREAD

**Issue by crazyvan25** [gatling/gatling#3958] opened 2020-09-08 14:00 UTC
Hi, I've just upgraded to 3.3.1 from 2.3.0. Everything worked okay with the exception of one scenario. Here is a minimal example:

```
package upgrade

import io.gatling.core.Predef._
import io.gatling.http.Predef.http

import scala.concurrent.duration._

class TokenInfoSimulation extends Simulation {

  private val baseProtocol = http
    .userAgentHeader("Gatling")
    .acceptEncodingHeader("gzip,deflate")

  private val tokenInfoScenario =
    scenario("Token Info")
      .exec(
        http("Token Info")
          .get("https://access.stage.api.bbc.com/v1/user/tokenInfo")
      )

  setUp(
    tokenInfoScenario
      .inject(
        constantUsersPerSec(5) during (10 seconds)
      )
      .protocols(baseProtocol)
  )

}
```

All of the requests consistently fail with Premature close:

2020-09-08 14:34:43                                          10s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=0      KO=50    )
> Token Info                                               (OK=0      KO=50    )
---- Errors --------------------------------------------------------------------
> j.i.IOException: Premature close                                   50 (100.0%)

And here is the log:
[simulation.log](https://github.com/gatling/gatling/files/5188727/simulation.log)

Not sure if this is useful, I was previously on:
```
scalaVersion := "2.11.7"
libraryDependencies += "io.gatling" % "gatling-test-framework" % "2.3.0" % "test"
```

and now:
```
scalaVersion := "2.12.0"
libraryDependencies += "io.gatling" % "gatling-test-framework" % "3.3.1" % "test"
```

**Comment by slandelle** [comment] 2020-09-08 14:14
Could you please share a sample target app? Without one, there's no way to execute a test that hits "https://localhost/v1/user/tokenInfo".

**Comment by crazyvan25** [comment] 2020-09-08 15:09
Thanks for getting back to me! I've updated the example

**Comment by slandelle** [comment] 2020-09-08 15:23
It looks like this issue was present in 3.3.1 but was already fixed in master/upcoming 3.4.0.

**Comment by crazyvan25** [comment] 2020-09-08 15:26
Awesome, thanks!

**Comment by slandelle** [comment] 2020-09-08 15:31
Pretty swamped before the upcoming release train, so I don't have time to look for the duplicated issue :(

**Comment by slandelle** [comment] 2020-09-08 15:35
Duplicate of #3746

**Closed by slandelle** 2020-09-08 15:35 UTC
Labels: Module - HTTP, Type - Bug
