### ISSUE TITLE
Array index out of bounds on generating report

### ISSUE THREAD

**Issue by pebert** [gatling/gatling#3397] opened 2017-12-05 21:48 UTC
Hi all, get an error when trying to generate reports.  It's pretty consistently happening on tests that I run where there are some connection/request timeouts.  I can upload the logs from the test where this happens if you need to reproduce.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -836101361
	at io.gatling.charts.stats.buffers.CountsBuffer.update(CountBuffer.scala:35)
	at io.gatling.charts.stats.buffers.ResponsesPerSecBuffers.updateResponsesPerSecBuffers(ResponsesPerSecBuffers.scala:32)
	at io.gatling.charts.stats.buffers.ResponsesPerSecBuffers.updateResponsesPerSecBuffers$(ResponsesPerSecBuffers.scala:31)

**Comment by slandelle** [comment] 2017-12-05 21:52
When creating an issue, you are asked to provide the version of Gatling you're using and a way for us to reproduce. Please do so.

**Comment by pebert** [comment] 2017-12-05 22:42
The data was generated with 2.2.2,  I found that using 2.3.0 to try and generate the report also errors, but that might be because it was generated with 2.2.2

A attaching the logs
[gatling-err.tar.gz](https://github.com/gatling/gatling/files/1533233/gatling-err.tar.gz)

**Comment by slandelle** [comment] 2017-12-06 08:24
> I found that using 2.3.0 to try and generate the report also errors

Indeed, the data is the file is indeed invalid.

> that might be because it was generated with 2.2.2

I suspect this is something that was fixed since. Please upgrade to 2.3.0 and report back if you can still reproduce.

**Comment by slandelle** [comment] 2017-12-08 13:54
@pebert ping

**Comment by pebert** [comment] 2017-12-08 14:32
The dependencies of the project don't allow me simply upgrade the version (lots of build errors).  Can you tell me what is wrong with the data file?  I saw an issue earlier with 0s ending in timestamps, which might explain how I can't always reproduce this.

**Comment by slandelle** [comment] 2017-12-08 14:36
> I saw an issue earlier with 0s ending in timestamps

Yes, that's the issue. I suspect this is caused by an old bug in our HTTP client that's been fixed for a long time.

Closing for now. Please reach out if you can upgrade and still reproduce.

**Closed by slandelle** 2017-12-08 14:36 UTC
Labels: Waiting for User
