### ISSUE TITLE
Websocket `await` hangs indefinitely despite reached timeout

### ISSUE THREAD

**Issue by kamilkloch** [gatling/gatling#4441] opened 2023-07-06 15:08 UTC
The following code hangs indefinitely, if only less than two messages have been received. In other woards, `await(finiteDuration)` has no effect.

```scala
exec(
      ws("...")
        .sendText("...")
        .await(1.seconds)(
          ws.checkTextMessage("checkFrame").silent,
          ws.checkTextMessage("checkFrame").silent
        )
```

If the two checks are packaged in separate awaits, timeouts work correctly:
```scala
exec(
      ws("...")
        .sendText("...")
        .await(1.seconds)(ws.checkTextMessage("checkFrame").silent)
        .await(1.seconds)(ws.checkTextMessage("checkFrame").silent)
       )
```

**Comment by slandelle** [comment] 2023-07-06 15:18
Duplicate of #4434

**Closed by slandelle** 2023-07-06 15:18 UTC
